### ISSUE TITLE
Logs are not in standard location

### ISSUE THREAD

**Issue by skibum55** [cloudfoundry/garden-runc-release#100]
Hi there! Thanks for taking time to open an Issue.
Please fill out as much of the following information as you can.

# Description

Was doing some troubleshooting of grootfs mounts and had a hard time finding the logs.  Why are some [logs](https://github.com/cloudfoundry/garden-runc-release/blob/master/jobs/garden/templates/bin/garden_start.erb#L14) going to a _monit_ directory instead of the jobs directory?

# Environment

* garden-runc-release version: 
    garden-runc            1.16.4*       5cf0a27+
    grootfs                0.30.0*       46b860c
* IaaS: 
   GCP/K8S
* Stemcell version: 
   Xenial 97.18
* Kernel version: (`uname -r` from within VM running Garden prints this information)
   4.15.0-1017-gcp

**Comment by georgethebeatle** [comment]
Hi @skibum55!

Thanks for reporting this issue! All garden related logs can now be found in garden's log dir. Look for `garden_start.stdout.log` and `garden_start.stderr.log`
