### ISSUE TITLE
The gosec tool found issues in garden-runc-release-1.16.6

### ISSUE THREAD

**Issue by Wayne-H-Ha** [cloudfoundry/garden-runc-release#103]
Is it OK if the gosec tool found the following HIGH severity, MEDIUM confidence issues against garden-runc-release-1.16.6 with details:
  
Use of weak random number generator (math/rand instead of crypto/rand)

```
{
 "file": "./packages/code.cloudfoundry.org/grootfs/integration/utils.go",
 "code": "rand.Int()",
 "line": "146"
},
{
 "file": "./packages/code.cloudfoundry.org/grootfs/base_image_puller/base_image_puller.go",
 "code": "rand.Int()",
 "line": "220"
},
{
 "file": "./packages/github.com/containerd/containerd/snapshots/testsuite/helpers.go",
 "code": "rand.Int()",
 "line": "54"
},
{
 "file": "./packages/code.cloudfoundry.org/grootfs/testhelpers/utils.go",
 "code": "rand.Int()",
 "line": "20"
},
{
 "file": "./packages/github.com/containerd/containerd/snapshots/testsuite/testsuite.go",
 "code": "rand.Int()",
 "line": "825"
},
```

There are 3 of the 5 files belong to test helper/suite which I assume we can ignore?  What about the other 2 files?

**Comment by BooleanCat** [comment]
Hi @Wayne-H-Ha - Actually 4 of these 5 results are in test packages (notice the first is a subdir of "integration". Looking at the use of rand.Int() in `base_image_puller.go`, it looks like it's used in conjunction with an image chain ID and the current unix timestamp in nanoseconds to generate a temporary directory for which to unpack container image layers into.

This directory is generated using the mkdir syscall and is appropriately unique such that:

1. a name collision with parallel creates is *extremely* unlikely
1. a name collision would result in a mkdir syscall failure and unpack would fail

Do you have any specific concerns about the use of rand.Int here?

**Comment by Wayne-H-Ha** [comment]
Thanks for the quick response. I have no more concern about the use of rand.Int() in base_image_puller.go.  I am closing this issue for now.
