### ISSUE TITLE
garden fails to start after upgrade: "timed out waiting for container kill"

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/garden-runc-release#108]
## Description
Sadly I don't have a ton of detail, but the rel-int team ran into a similar issue.

Re-deployment (not upgrading any garden components) failed in the post-deploy step, with `rep` failing post deploy.  Rep logs report inability to find garden.

`pgrep containerd` showed 2 PIDs--one was apparently a stuck container.  Garden logs reported the same error once every 2 minues for a long long time (total count: 1416)
```
{"timestamp":"2018-11-29T19:57:17.935639633Z","level":"error","source":"guardian","message":"guardian.api.garden-server.destroy.failed","data":{"error":"timed out waiting for container kill: containerdProcess=9e353214-da61-4e33-625e-0754, processID=15049","handle":"9e353214-da61-4e33-625e-0754","session":"1.1.1851"}}
{"timestamp":"2018-11-29T19:59:19.174449049Z","level":"error","source":"guardian","message":"guardian.api.garden-server.destroy.failed","data":{"error":"timed out waiting for container kill: containerdProcess=9e353214-da61-4e33-625e-0754, processID=15049","handle":"9e353214-da61-4e33-625e-0754","session":"1.1.1854"}}
```

`monit stop containerd` and `kill -9 15049` healed the vm and allowed subsequent cell restart to succeed, but of course made further diagnostic steps difficult.  I didn't observe whether the process was in d state or not.

## Environment

* garden-runc-release version: 1.17.0
* IaaS:
* Stemcell version: xenial 170.9
* Kernel version: 4.15.0-39-generic

## Steps to reproduce
🤷‍♂️ 

## Logs
see above
Also, see this thread in the diego slack channel: https://cloudfoundry.slack.com/archives/C02FM2BPE/p1543518394295900

**Comment by gcapizzi** [comment]
We have been unable to reproduce the problem. We tried deploying a CF with the nfs ops files (which anecdotally seems to be the commonality between occurrences of this issue) and pushed 5 apps, then redeployed a bunch of times. It just worked.

The suspicion we have (based on armchair engineering) is that since the following is true:

1. garden reports it fails to kill containerd containers and timing out
2. you are able to manually kill the container processes

We can think of 2 reasons this might occur, either:

1. the processes were unkillble (D state) when containerd tried to kill them but not when you killed them
2. containerd is killing the wrong processes (which we have observed in  CI before, but only when we have multiple garden servers running at the same time)

In order to look more into this we really need an env with this occurring. If you or relint could provide a repro env that would be super.

**Comment by julian-hj** [comment]
Another curious thing I noticed...when Garden is in the "flapping" state, where monit is sending SIGTERM to it over and over, it seems to be getting killed off every 20 seconds or so. 
Is that expected?  

I would have thought that it should stay up for 2 minutes, based on 

```
  if failed unixsocket <%= p("garden.listen_address") %>
    with timeout 5 seconds for 12 cycles
    then restart
```

in garden's monit file, and 

```
set daemon 10
``` 

(suggesting a 10 second cycle type) in `/var/vcap/bosh/etc/monitrc`

**Comment by gcapizzi** [comment]
We've had a chance to spend some time on a relint environment exposing a similar problem: Garden times out while trying to kill containers at startup, crashes and gets restarted after 2 minutes.

It looks like the cgroups for the _"unkillable"_ container are misconfigured. In particular, while the process is correctly associated with the `/garden/[container-id]` sub-cgroup (as specified in `cgroupsPath` in the `config.json` for the container) for some of the cgroups, it is not for others:

```
# cat /proc/[garden-init-pid]/cgroup
12:blkio:/ <- wrong
11:hugetlb:/garden/[container-id]
10:rdma:/
9:freezer:/garden/[container-id]
8:perf_event:/garden/[container-id]
7:net_cls,net_prio:/garden/[container-id]
6:memory:/ <- wrong
5:cpuset:/garden/[container-id]
4:pids:/ <- wrong
3:cpu,cpuacct:/ <- wrong
2:devices:/system.slice/runit.service <- wrong
1:name=systemd:/system.slice/runit.service/garden/[container-id]
```

In particular, the `devices` cgroup is used by `runc` to determine which processes to kill when deleting a container. Unfortunately, `runc` is not aware of the cgroup misconfiguration! In the `state.json` file for the container, we see the `devices` cgroup path to be stored as `/sys/fs/cgroup/devices/system.slice/runit.service/garden/[container-id]`.

### What we believe is happening:
- Garden asks Containerd to delete the container
- Containerd asks `runc` to delete the container
- `runc` looks inside `/sys/fs/cgroup/devices/system.slice/runit.service/garden/[container-id]/cgroup.procs` to find the processes to kill
- `/sys/fs/cgroup/devices/system.slice/runit.service/garden/[container-id]/cgroup.procs` is empty, so `runc` just returns
- Containerd is left waiting for the container to terminate forever
- Garden times out and crashes

**Comment by julian-hj** [comment]
Here are some other oddities I am observing based on our environment (which is stuck again after bosh restarting the cell):

1) after restart, all the containers that were running before restart are still hanging around in somewhat diminished form

2) The one garden gets stuck on at restart (the first one it tries to clean up) is similarly empty, but it still has a garden-init process running in it

3) it is the garden init process that garden asks to signal with a sigkill (not sure if this is significant or not)

log line where garden hangs:

```
{"timestamp":"2018-12-06T18:12:38.889243314Z","level":"info","source":"guardian","message":"guardian.start.clean-up-container.destroy.started","data":{"handle":"21c7eb48-d1ff-4f5f-76e0-3c6e","session":"4.2.1"}}
```

```
# systemd-cgls systemd:/system.slice/runit.service/garden/21c7eb48-d1ff-4f5f-76e0-3c6e
Controller systemd; Control group /system.slice/runit.service/garden/21c7eb48-d1ff-4f5f-76e0-3c6e:
└─309315 /tmp/garden-init

# cat /sys/fs/cgroup/devices/system.slice/runit.service/garden/21c7eb48-d1ff-4f5f-76e0-
# cat /proc/309315/cgroup | grep name
1:name=systemd:/system.slice/runit.service/garden/21c7eb48-d1ff-4f5f-76e0-3c6e
#
```

I'm not really sure what I am looking at though--it kind of seems like garden-init is half-in/half-out of the cgroup?

normally the group for one of our brokers that is running and healthy should look like this:

```
# systemd-cgls systemd:/system.slice/runit.service/garden/7bb2f06a-7d65-4813-4618-d88e
Controller systemd; Control group /system.slice/runit.service/garden/7bb2f06a-7d65-4813-4618-d88e:
├─318589 /tmp/garden-init
├─320175 bash -c ./start.sh
├─320266 bin/nfsbroker --listenAddr=0.0.0.0:8080 --servicesConfig=./services.json --dbDriver=mysql --dbHostname=sql-db.service.cf.internal --dbPort=3306 --dbName=nfs-broker --dbCACert
└─320274 /tmp/lifecycle/diego-sshd --allowedKeyExchanges= --address=0.0.0.0:2222 --allowUnauthenticatedClients=false --inheritDaemonEnv=true --allowedCiphers= --allowedMACs= --logLeve
```

but after a bosh restart of the cell, the same cgroup looks like this:

```
# systemd-cgls systemd:/system.slice/runit.service/garden/7bb2f06a-7d65-4813-4618-d88e
Controller systemd; Control group /system.slice/runit.service/garden/7bb2f06a-7d65-4813-4618-d88e:
├─318589 /tmp/garden-init
└─320266 bin/nfsbroker --listenAddr=0.0.0.0:8080 --servicesConfig=./services.json --dbDriver=mysql --dbHostname=sql-db.service.cf.internal --dbPort=3306 --dbName=nfs-broker --dbCACertPath=./db_ca.crt
```

HTH 
🤷‍♂️

**Comment by julian-hj** [comment]
No, we don't have any way to confirm that.  Basically we just observed that every so often, we'd get these failures on restart.  We updated our ci to opt out of containerd a while back which made the issue go away, so we haven't reproduced it recently, and back when we were reproducing it, we weren't looking at cgroups.  So...it is entirely possible that it was only erroring after the first restart after a recreate.

**Comment by danail-branekov** [comment]
Hi @julian-hj 
There is a new Garden Runc release 1.18.0 that fixes the issue. Could you please verify that it works on your end?

Note that in order to upgrade to GRR 1.18.0 you would also need to bump cf-deployment to 7.1.0.

Thanks!
