### ISSUE TITLE
Garden running in BPM fails to start container with `preloaded+layer` RootFSPath/Image

### ISSUE THREAD

**Issue by flawedmatrix** [cloudfoundry/garden-runc-release#114]
## Description
(Relevant slack thread: https://cloudfoundry.slack.com/archives/C033RE5D6/p1544712031203900)
(Relevant story: https://www.pivotaltracker.com/story/show/162623662)

In our experimental CF environment with the [enable-bpm-garden.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/enable-bpm-garden.yml) and [enable-oci-phase-1.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/enable-oci-phase-1.yml) ops files specified, we noticed that apps were failing to push because of an x509 cert authority validation failure for the droplet coming from the blobstore. We found that grootfs was emitting this error when downloading the blob specified in the "top layer" in the Image with the `preloaded+layer` scheme.

Upon further investigation, we realized that removing the enable-bpm-garden.yml ops file was enough to allow CF apps to be pushed again.

We managed to isolate this issue in a bosh-lite with simply the two ops files mentioned above. With some modifications in the grootfs code, we managed to find out via debug logging that grootfs was quietly ignoring the certs used download the droplet!

```
Looking for TLS certificates and private keys in /var/vcap/jobs/garden/certs
Skipping scan of /var/vcap/jobs/garden/certs due to permission error: open /var/vcap/jobs/garden/certs: permission denied
```

After changing the permissions of the certs folder and its contents, we ran into another issue:
```
[CELL/0] ERR Cell <CELL-GUID> failed to create container for instance <INSTANCE-GUID>: running image plugin create: pulling the image: could not chown base directory: chown /var/vcap/data/grootfs/store/unprivileged/volumes/d0c304c91b12e0370507b57c8e1db8abc442e22260bb98f177383e9dab95ecdf-incomplete-1544830936651661436-7713884357668015356/home/vcap: operation not permitted
```

This seems like overall incompatibility between BPM and OCI Phase 1, but we believe garden should be able to work when both are configured.

## Environment

* garden-runc-release version: 1.17.1
* IaaS: Both GCP and bosh-lite
* Stemcell version: Ubuntu Xenial 170.12
* Kernel version: 4.15.0-32-generic

## Steps to reproduce
1. Deploy a fresh bosh-lite plus these two ops files:  [enable-bpm-garden.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/enable-bpm-garden.yml) and [enable-oci-phase-1.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/enable-oci-phase-1.yml)
2. Try to push any non-docker app.

**Comment by Callisto13** [comment]
## Resolution
The fix is available from GRR v1.19.0 onwards.
