### ISSUE TITLE
No containers in Diego Cell after garden restart

### ISSUE THREAD

**Issue by mma-pivotal** [cloudfoundry/garden-runc-release#122]
## Description
Hi Garden team, I tried `monit restart garden` on a diego cell and after that I noticed that all containers on that diego cell was evacuated (no container running on that cell anymore), from rep.log I found the following
```
{"timestamp":"2019-01-30T12:08:53.279511382Z","level":"error","source":"rep","message":"rep.request.auction-fetch-state.auction-state.failed-garden-health-check","data":{"method":"GET","request":"/state","session":"688.1.1"}}
```
So seems like auctioneer cannot check the health status of this particular diego cell and I assume this could explain why all containers were gone.
My question is whether this is expected behavior and if yes what is the correct procedure to restart garden job in diego_cell?

## Environment

* PAS - 2.2.6
* garden-runc-release version: 1.13.3
* Enabled configuration: 
* IaaS: vSphere
* Stemcell version: ubuntu-trusty 3586.42
* Kernel version: 

## Steps to reproduce
1) Login into Diego Cell and su to root
2) Monit stop garden
3) Wait 2 or 3 mins
4) Monit start garden
5) Wait 2 or 3 mins
6) /var/vcap/jobs/rep/packages/runc/bin/runc list (there should be no containers)

## Logs
grep failed-garden /var/vcap/sys/log/rep/rep.stdout.log (you should see something similar to below)
```
{"timestamp":"2019-01-30T12:08:53.279511382Z","level":"error","source":"rep","message":"rep.request.auction-fetch-state.auction-state.failed-garden-health-check","data":{"method":"GET","request":"/state","session":"688.1.1"}}
{"timestamp":"2019-01-30T12:09:23.421690173Z","level":"error","source":"rep","message":"rep.request.auction-fetch-state.auction-state.failed-garden-health-check","data":{"method":"GET","request":"/state","session":"689.1.1"}}
{"timestamp":"2019-01-30T12:09:53.557637653Z","level":"error","source":"rep","message":"rep.request.auction-fetch-state.auction-state.failed-garden-health-check","data":{"method":"GET","request":"/state","session":"690.1.1"}}
```

**Comment by mma-pivotal** [comment]
If possible please assign this ticket to Claudia or Thomas Godkin.

**Comment by BooleanCat** [comment]
Hi there.

Garden has a feature that instructs it to destroy containers on startup. This feature is turned on when deployed as part of cloud foundry. So performing a `monit restart garden` and seeing all of the containers be destroyed is expected behaviour.
