### ISSUE TITLE
Document how to look up container nic from container guid

### ISSUE THREAD

**Issue by AnuRam123** [cloudfoundry/garden-runc-release#128]
## Description
We have a monitoring script in our Diego cells which is very CPU intensive, the root cause is looking up virtual nic when we moved from warden containers to Diego Cells and we need a method to know how the container is mapped to the NIC's

We need documentation on how it is used and the implementation so our script can be modified to make it more optimum.

**Comment by adobley** [comment]
Hi @AnuRam123, what is the root problem you are trying to solve by knowing how the containers are mapped to the NIC's? Are you looking for the IP on the overlay, or the Diego Cell IP which is DNATed to the container, or something else?

**Comment by AnuRam123** [comment]
sorry just saw this.. well the main problem i am trying to solve is the CPU utilization that is caused by a monitoring script, this script had to be changed when we moved from warden containers to Diego , 
The current CPU usage issue is caused by the new implementation of Diego. In the previous version of Cloud Foundry using Warden, there was a local file always showing the mapping of container and virtual NIC. The developer didnt know the API or how to get it in Diego so the logic got very complicated resulting in very high CPU. @julz  said that we just need the documentation so our developers can fix this monitoring script.
@julz

**Comment by AnuRam123** [comment]
The main detail needed is to know how much network each container on each cell is using. This is the  piece of code that got complicated with the new implementation of the monitoring script.
