### ISSUE TITLE
Possible AppArmor issue (bosh-cli fails trying to print progressbar to screen/terminal)

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/garden-runc-release#13]
## Description

We have a Concourse setup running with v1.6.0 and recently upgraded to using garden-runc v0.5.0 for its workers.
We noticed that since the upgrade some of our build jobs on these workers have been failing, to be more specific they fail when they try to run the bosh-cli command `bosh upload stemcell <filename>`.
During the stemcell upload the bosh-cli will try to print a progressbar to the screen/terminal, and fails with the error message `negative argument.`:

```
Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-openstack-kvm-ubuntu-trusty-go_agent
Version: 3262.5

Checking if stemcell already exists...
No

Uploading stemcell...

negative argument.

Usage: upload stemcell <stemcell_location> [--skip-if-exists] [--fix] [--sha1 SHA1] [--name NAME] [--version VERSION]
```

I think this might be an AppArmor issue?
While trying to pinpoint the issue, I downgraded our Concourse workers back to garden-runc v0.4.0 that does not yet have AppArmor, and suddenly the bosh-cli was working again perfectly fine, printing the progressbar with no problem.
Or could there be something else where v0.4.0 and v0.5.0 differ that might cause this issue?
What's also weird is that when I use the `fly` cli to hijack into the container and manually run the bosh-cli command, it will work (on bosh v0.4.0 and v0.5.0)!
Looks to me like it could have something to do with the terminal? Unfortunately I'm no expert at this and could not figure out further what might be the cause.

## Steps to reproduce

* concourse v1.6.0
* garden-runc v0.5.0
* bosh-cli v1.3262.4.0
* build job that runs `bosh stemcell upload <filename>`
* docker-image used for build job: https://github.com/JamesClonk/concourse-workspace/blob/master/Dockerfile | ubuntu:16.04

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#128710767](https://www.pivotaltracker.com/story/show/128710767) Possible AppArmor issue (bosh-cli fails trying to print progressbar to screen/terminal)


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by georgethebeatle** [comment]
It is definitely related to terminals @JamesClonk. It has nothing to do with AppArmour. It seems that we are no longer setting default terminal size - definitely a bug. You can tack progress in the issue linked above.

**Comment by garden-gnome** [comment]
Hello again!

All stories related to this issue have been accepted, so I'm going to automatically close this issue.

At the time of writing, the following stories have been accepted:

* [#128710767](https://www.pivotaltracker.com/story/show/128710767) Possible AppArmor issue (bosh-cli fails trying to print progressbar to screen/terminal)


If you feel there is still more to be done, or if you have any questions, leave a comment and we'll reopen if necessary!

**Comment by jadekler** [comment]
Hello! We have just run into this issue @georgethebeatle. Should we be upgrading bosh or something to fix this issue?

**Comment by ematpl** [comment]
@jadekler Based on the release notes and the [Garden tracker](https://www.pivotaltracker.com/n/projects/1158420), I think this TTY issue is fixed in [garden-runc v0.7.0](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v0.7.0), so you could try upgrading your Concourse deployment to use that version.

Best,
Eric

**Comment by jadekler** [comment]
Thanks @ematpl

**Comment by JamesClonk** [comment]
@jadekler I can confirm this, I'm running the latest Concourse together with garden-runc 0.7.0 and it works fine 👍
