### ISSUE TITLE
Zombie runc processes!

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/garden-runc-release#136]
## Description

While playing around with garden to write a talk - I noticed a bunch of zombie runc processes. This surprised me and I found this issue in the runc repo: https://github.com/opencontainers/runc/issues/2022

## Environment

* garden-runc-release version: 1.19.1
* Enabled configuration: N/A
* IaaS: N/A
* Stemcell version: N/A
* Kernel version: N/A

## Steps to reproduce

Observe `ps auxf` while creating containers and running some processes in them.

## Cause

https://github.com/opencontainers/runc/issues/2022 probably

## Resolution

Bump runc to `v1.0.0-rc7`+

**Comment by BooleanCat** [comment]
I've bumped runc.

**Comment by Callisto13** [comment]
Cool I remember seeing this a lot but never had time to dig in!
