### ISSUE TITLE
pkg-config fails to compile on Bionic stemcells

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/garden-runc-release#145]
Disclaimer: I'm aware Bionic stemcells are not published anywhere yet, I'm creating this issue to track a specific failure when compiling against them though.

We have a discussion in slack about getting y'all access to them, and stories in our backlog (https://www.pivotaltracker.com/story/show/167051076)

## Description

We updated cf-deployment to use a bionic stemcell, and tried to deploy. `pkg-config` failed to compile (logs below)

## Environment

We used vanilla cf-deployment.

* garden-runc-release version: 1.19.2
* Enabled configuration: n/a
* IaaS: GCP
* Stemcell version: Bionic
* Kernel version: n/a

## Steps to reproduce

* Switch cf-deployment to Bionic
* `bosh deploy`

## Logs

[garden-pkg-config.err.log](https://github.com/cloudfoundry/garden-runc-release/files/3356424/garden-pkgconfig.err.log)

**Comment by georgethebeatle** [comment]
Hi @aashah,

We fixed the compilation issues by bumping pkg-config and automake packages. You can use latest grr (develop branch) or wait for next release.
