### ISSUE TITLE
Max containers limits not correctly observered.

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/garden-runc-release#149]
## Description
We are using garden-runc 1.19.5 we have set max-containers to 200 but when the containers get to about 95 we get errors saying max-containers reached.

## Environment

* garden-runc-release version: 1.19.5
* Enabled configuration: containerd
* IaaS: softlayer
* Stemcell version: 456.12
* Kernel version: 4.15.0-55-generic

## Steps to reproduce
we have cells with 95 containers and after that we are getting errors that garden is saying too many containers.

## Logs
```
{"timestamp":"2019-08-29T12:43:44.339585707Z","level":"info","source":"guardian","message":"guardian.create.containerizer-create.start","data":{"handle":"9e03f69b-8f3a-4c38-6119-4ae0","session":"11148095.4"}}
{"timestamp":"2019-08-29T12:43:44.341541117Z","level":"info","source":"guardian","message":"guardian.create.containerizer-create.Annotations before update","data":{"Annotations":null,"handle":"9e03f69b-8f3a-4c38-6119-4ae0","id":"9e03f69b-8f3a-4c38-6119-4ae0","session":"11148095.4"}}
{"timestamp":"2019-08-29T12:43:44.341587441Z","level":"info","source":"guardian","message":"guardian.create.containerizer-create.Annotations after update","data":{"Annotations":{"container-type":"garden-init"},"handle":"9e03f69b-8f3a-4c38-6119-4ae0","id":"9e03f69b-8f3a-4c38-6119-4ae0","session":"11148095.4"}}
{"timestamp":"2019-08-29T12:43:44.377941950Z","level":"error","source":"guardian","message":"guardian.api.garden-server.create.failed","data":{"error":"max containers reached","request":{"Handle":"27df02a6-5607-4335-628c-8749","GraceTime":0,"RootFSPath":"","BindMounts":[{"src_path":"/var/vcap/data/rep/shared/garden/download_cache/38b2a7ccd052cc6ca87458d02a7c6c7a-1566588116797712136-124974.d","dst_path":"/tmp/lifecycle"},{"src_path":"/var/vcap/data/rep/shared/garden/trusted_certs","dst_path":"/etc/cf-system-certificates"},{"src_path":"/var/vcap/packages/proxy","dst_path":"/etc/cf-assets/envoy"},{"src_path":"/var/vcap/data/rep/shared/garden/proxy_config/27df02a6-5607-4335-628c-8749","dst_path":"/etc/cf-assets/envoy_config"},{"src_path":"/var/vcap/data/rep/shared/garden/instance_identity/27df02a6-5607-4335-628c-8749","dst_path":"/etc/cf-instance-credentials"},{"src_path":"/var/vcap/packages/healthcheck","dst_path":"/etc/cf-assets/healthcheck"}],"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{"limit_in_shares":30},"disk_limits":{"inode_hard":200000,"byte_hard":1073741824,"scope":1},"memory_limits":{"limit_in_bytes":268435456},"pid_limits":{"max":1024}}},"session":"1.1.301111"}}```

```
## Date
Thu Aug 29 15:16:32 UTC 2019
## Uptime
 15:16:32 up 5 days, 16:52,  1 user,  load average: 4.71, 4.38, 4.78
## Garden Version
8d2172953e10088b80bc3bbcdae53118bf6f9cbb
## Hostname
67c29f9d-f0e7-4ccd-a053-912ebfb0dead
## Memory Usage
              total        used        free      shared  buff/cache   available
Mem:          32163        7314        1374         385       23473       22882
Swap:         32162        3683       28479
Total:        64326       10998       29853
## Kernel Details
Linux 67c29f9d-f0e7-4ccd-a053-912ebfb0dead 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
## Monit Summary
The Monit daemon 5.2.5 uptime: 5d 16h 48m

Process 'garden'                    running
Process 'rep'                       running
Process 'route_emitter'             running
Process 'netmon'                    running
Process 'vxlan-policy-agent'        running
Process 'silk-daemon'               running
Process 'loggr-udp-forwarder'       running
Process 'bosh-dns-adapter'          running
Process 'loggregator_agent'         running
Process 'loggr-forwarder-agent'     running
Process 'prom_scraper'              running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'mod_vms'                   running
Process 'sssd'                      running
Process 'incrond'                   running
Process 'filebeat'                  running
System 'system_localhost'           running
## Number of Containers
93
## Number of Open Files
```

## Cause
somehow the container limit comparison is incorrect

## Resolution

**Comment by andrew-edgar** [comment]
more info ...

```
diego-cell/211a5393-7536-4a7d-a270-bfe13a58bae7:/var/vcap/bosh_ssh/bosh_af33fee23831415# /var/vcap/packages/containerd/bin/ctr -a /var/vcap/sys/run/containerd/containerd.sock -n garden tasks ls | wc -l
105
```
```
diego-cell/211a5393-7536-4a7d-a270-bfe13a58bae7:/var/vcap/bosh_ssh/bosh_af33fee23831415# /var/vcap/packages/containerd/bin/ctr -a /var/vcap/sys/run/containerd/containerd.sock -n garden containers ls | wc -l
200
```

**Comment by andrew-edgar** [comment]
here is the rest of the dontpanic output ...

```
## Number of Open Files
Failure: timed out after 10s
## Max Number of Open Files
102400
## Disk Usage
## List of Open Files
Failure: timed out after 10s
## Process Information
## Process Tree
## Kernel Messages
## Network Interfaces
## IP Tables
## NAT IP Tables
Failure: timed out after 10s
## Mount Table
## Garden Depot Contents
## XFS Fragmentation
## XFS Info
## Slabinfo
## Meminfo
## IOSTAT -xdm (slow)
## VMSTAT -s
## VMSTAT -d (slow)
## VMSTAT -a (slow)
## Mass Process Data
## Kernel Log
## Monit Log
## Syslog
## Garden Config
## Garden Logs
```

Not great with the "timeouts"?

**Comment by gcapizzi** [comment]
We think this is fixed! (See [tracker issue](https://www.pivotaltracker.com/story/show/168196460)). Closing.
