### ISSUE TITLE
Issues with  PAS 2.6 and running Go docker images with containerd enabled

### ISSUE THREAD

**Issue by swagataroy** [cloudfoundry/garden-runc-release#150]
Through many iterations of troubleshooting, we have discovered that any docker base image we try, if built on a local workstation with or without DNS/troubleshooting tooling, will deploy correctly. Anything with or without tooling where the image is created via our typical gitlab runner build (on traditional vsphere or on pks runners) both result in a docker image where DNS is not resolvable and fails to start.
This would require major rework to port it to using buildpacks. That being said, we have some concern that this behavior may be related to containerd cutover (which we opted into with the 2.6 upgrade) vs garden runc. 

 We reproduced the issue with the SAME docker image docker
PAS 2.5 – app starts fine
PAS 2.6 (with containerd) – app FAILS to resolve DNS for dependencies and fails to start.
We were able to confirm that removing the *containerd* tag in our sandbox environment corrected the DNS lookup issue. This 100% puts the concern on Containerd in 2.6. Internal conversations suggested:
 What does the ctl cli step look like, and is there any sense in going that direction versus just disabling containerd for this release until we are able to validate and test at larger scale?

Are their issues with Name resolution running PAS on 2.6 with containerd?

**Comment by julz** [comment]
Hi @swagataroy - we're going to start looking at this soon, but it would likely speed up our attempts to reproduce significantly if you were able to provide an image which re-produces the problem (perhaps a test image with no production code produced by the same pipeline?). Thanks!

**Comment by kieron-pivotal** [comment]
Hi @swagataroy - we see that /etc/hosts and /etc/resolv.conf are overwritten in
both containerd and non-containerd modes, so we aren't sure how to reproduce
the behaviour you're seeing. It would be very good to have a reproduction image
or more details about how the DNS resolution is being configured in the docker
image.

As an aside, are you aware of the garden manifest properties
garden.additional_host_entries and garden.additional_dns_servers where you can
tweak /etc/hosts and /etc/resolv.conf for all containers?

cc: @danail-branekov

**Comment by julz** [comment]
hi @swagataroy - we're not sure how to proceed since we can't reproduce this. Please do feel free to re-open this issue or open a new issue if you can give us a docker image that reproduces the issue. Thanks!
