### ISSUE TITLE
Garden failing with error "open mnt namespace: No such file or directory"

### ISSUE THREAD

**Issue by pivotal-mariusz-kaszewiak** [cloudfoundry/garden-runc-release#154]
Issue happens when try to push application:

> Error staging application: Staging error: staging failed.

Problem its happening randomly it may work after second push try. By analysing logs provided it looks that the staging was successful, droplet was uploaded back to blob-store successfully, however an error happened when cleaning up the staging container. Please see attached logs. Diego garden and rep logs may indicate that there is something broken with garden. It looks that it tries to destroy the container that was already destroyed

## Environment
 Issue started happening after upgrade from PAS 2.5.9 to PAS 2.6.9
* garden-runc-release version: garden-runc-1.19.9-ubuntu-xenial-315.146.tgz
* Enabled configuration: containerd
* IaaS:
* Stemcell version: 
* Kernel version: 

## Steps to reproduce

Issue is happening randomly and with different buildpacks so the steps to reproduce aren't really known.

## Logs

```
{"timestamp":"2020-02-20T07:44:28.079314426Z","level":"info","source":"guardian","message":"guardian.api.garden-server.stream-out.streamed-out","data":{"handle":"c1bc6574-3209-4e3c-b70c-2c8db8bb27de","session":"1.1.8481","source":"/tmp/result.json","user":"root"}}
{"timestamp":"2020-02-20T07:44:28.079597426Z","level":"error","source":"guardian","message":"guardian.stream-out.wait","data":{"error":"exit status 1","handle":"c1bc6574-3209-4e3c-b70c-2c8db8bb27de","path":"/tmp/result.json","pid":0,"session":"218731","stdout":"open mnt namespace: No such file or directory\n","user":"root"}
{"timestamp":"2020-02-20T07:44:28.106365627Z","level":"info","source":"guardian","message":"guardian.destroy.start","data":{"handle":"c1bc6574-3209-4e3c-b70c-2c8db8bb27de","session":"218733"}}
```

## Cause

We suspect some threads are not well-synchronized below, especially when the diego cells disk I/O is not fast enough

### Source Code

```
// StreamOut stream files from the container
func (c *Containerizer) StreamOut(log lager.Logger, handle string, spec garden.StreamOutSpec) (io.ReadCloser, error) {
    ...
	stream, err := c.nstar.StreamOut(log, state.Pid, spec.Path, spec.User)
	if err != nil {
		log.Error("nstar-failed", err)
		return nil, fmt.Errorf("stream-out: nstar: %s", err)
	}
	return stream, nil
}
```

```
func (n *nstar) StreamOut(log lager.Logger, pid int, path, user string) (io.ReadCloser, error) {
    ...
cmd := exec.Command(n.NstarBinPath, n.TarBinPath, fmt.Sprintf("%d", pid), n.streamUser(user), sourcePath, compressPath)
	cmd.Stdout = writer
	cmd.Stderr = errOut
	if err := n.CommandRunner.Background(cmd); err != nil {
		return nil, fmt.Errorf("error streaming out: %v. Output: %s", err, errOut.String())
	}
	writer.Close()
	go func() {
		if err := n.CommandRunner.Wait(cmd); err != nil {
			log.Error("wait", err, lager.Data{
				"pid":    pid,
				"path":   path,
				"user":   user,
				"stdout": errOut.String()})
		}
	}()
	return reader, nil
}
```

**Comment by kieron-pivotal** [comment]
Attaching fuller logs from a previous failure - handle ea2c0b84-3df0-4ddd-b619-d9d49deb68d0

https://drive.google.com/a/pivotal.io/file/d/1UdS8iXgIeW1zVkuLihlRmzsjM-rHip09/view?usp=sharing

**Comment by kieron-pivotal** [comment]
This issue was seen in garden v1.19.9. Underlying cause is the containerd server call to the containerd-shim, which is getting a 'context deadline exceeded' timeout.

Retry logic was introduced in v1.19.10, and we have improved this and added more logging for the next release (probably v.1.19.11).

Closing the issue now as we believe the retry logic should make things better. If you see this again with the latest version, please re-open.
