### ISSUE TITLE
Please complete the Cloudfoundry Component Log Timestamp Audit - as per: CF-RFC#030

### ISSUE THREAD

**Issue by heyjcollins** [cloudfoundry/garden-runc-release#155]
Hi There Gardners!

In an effort to assure Diego and **all** its subcomponents use a timestamp that's consistent with all other CloudFoundry components as per [CF-RFC#030](https://docs.google.com/document/d/13pQgvxbGVsMKFGZjk5vqkAdi1AwwX5eZm1TQ9pPC8WM/edit), I've created an issue here that's meant to represent all releases the Garden team is responsible for.

A little action is required from y'all on this x-component-team effort.

### First 
Please complete [this audit](https://docs.google.com/spreadsheets/d/1OuwZMUGYiVxZbbtB0Hv_I4AlvdAuPoJ1kYz_t3heNmw/edit?usp=sharing) as soon as possible.
- this [**tracker story template**](https://www.pivotaltracker.com/story/show/171752084) includes additional information and tools to aid in completing the audit

### Second
If additional work is required to meet the requirements outlined in CF-RFC#030 please create, and take action to address, github issue(s) describing the work required to meet those requirements. 

Thanks so much!

The CF-RFC#030 Authors (Josh Collins and Amelia Downs)

**Comment by gcapizzi** [comment]
@heyjcollins we're finally done on this! closing this issue, let me know if there is anything else that we need to do!
