### ISSUE TITLE
Too me many fds in /run directory

### ISSUE THREAD

**Issue by drahnr** [cloudfoundry/garden-runc-release#156]
## Description
No space on device when there clearly is space, causing all concourse resources to fail with no space errors when trying to create a fifo for stdin/stdout/stderr.

## Environment

* garden-runc-release  as supplied with concourse 6.0.0
* Enabled configuration: containerd
* IaaS: bare metal
* Kernel version: 5.5.13

## Steps to reproduce
So far I could not reproduce it, 10 days of concourse container usage with a lot of failing / timout / aborted builds seemed to be related. But I am not 100% sure what causes it, so far, it has been a single event.

## Cause
Root cause here is the directory limit of ~2e6 entries per directory IIRC.
The directory in question is /run/containerd/ holding all fifos for all containers.

## Resolution
Stop containerd, wipe the directory. This is a band aid.

**Comment by julz** [comment]
Hi @drahnr - can you check what you have [`cleanup_process_dirs_on_wait`](https://github.com/cloudfoundry/garden-runc-release/blob/develop/jobs/garden/spec#L196) set to?

**Comment by drahnr** [comment]
@julz cleanup_process_dirs_on_wait is unset in my configuration file, so the default of `false` should kick in

**Comment by julz** [comment]
Ok, it may be worth trying with that setting set to true which will cause processes to be cleaned up more quickly rather than only when the overall container is destroyed. At the very least, it'd help isolate the problem if we could see whether it still occurs with that set.

**Comment by drahnr** [comment]
Thanks!

As said, for the issue to appear, it might take 10d+

**Comment by yulianedyalkova** [comment]
@drahnr did you manage to reproduce the issue again?

**Comment by drahnr** [comment]
No, so far everything has been running smoothly.

**Comment by gcapizzi** [comment]
Hi @drahnr! We just had a closer look at the Concourse containerd integration, and we just realised that, actually, Concourse doesn't use Garden at all to talk to containerd 😅 You might want to raise this issue with them instead!

**Comment by drahnr** [comment]
But I am running containers through gdn, my gdn instance is a separate service and only gdn knows about concourse or is this information leaked through to concourse? I am slightly confused how the architecture works

**Comment by gcapizzi** [comment]
Concourse uses Garden to run containers when in default mode, but, AFAIK, not when in the experimental containerd mode. It's still worth going through them, they can raise a Garden issue in turn if they think it's necessary.
