### ISSUE TITLE
container.Run ignores supplementary groups when a User is specified

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#162]
When running a process with `container.Run`, if a `User` is specified in the `ProcessSpec`, Garden [looks up the user](https://github.com/cloudfoundry/guardian/blob/31e87d519d81cb27466089d03acf202fab979231/rundmc/users/lookup_linux.go#L24) by name and find its UID and GID, which it will use to generate the OCI process spec. 

Unfortunately, if the user belongs to any supplementary groups in `/etc/group`, Garden will [ignore those](https://github.com/cloudfoundry/guardian/blob/31e87d519d81cb27466089d03acf202fab979231/rundmc/processes/builder.go#L40) and won't add them to the OCI process spec.

This means any process executed as a specific user won't belong to the necessary supplementary groups.

To reproduce, try the following Docker image:

```Dockerfile
FROM centos:centos7

RUN groupadd -g 3135 ef_group && \
    adduser -m tomcat && \
    usermod -a -G ef_group tomcat

USER tomcat
```

Executing a shell in the container as the user `tomcat` and running `id` shows the absence of the `ef_group`, despite the `tomcat` user belonging to it!

```sh
$ gaol create -n cake -r <test-docker-image>
$ gaol shell -u tomcat cake
sh-4.2$ id
uid=17085(tomcat) gid=17085(tomcat) groups=17085(tomcat)
```

**Comment by kieron-pivotal** [comment]
Fixed in v1.19.16
