### ISSUE TITLE
Additional customization of tcp sysctl parameters is required for instances running in specialized internal networks.

### ISSUE THREAD

**Issue by rhardt-pivotal** [cloudfoundry/garden-runc-release#163]
## Description
Many users working on large enterprise networks stand up guardian containers containing applications that make outgoing connections to network endpoints over network devices which, for various reasons, may silently terminate the tcp connection.  

Because the source and destination are both under the control of the user, they can reason about an acceptable tcp timeout for these connections that differs from that in the linux `init_net` namespace, which is what guardian sets them to.  Common tcp_parameters used to adjust these timeouts are tcp_retries1 and tcp_retries2, c.f. https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html.

Some previous commits allowed the customization of the tcp_keepalive_time, tcp_keepalive_interval, and tcp_keepalive_probes tcp parameters and are working well for many users.  Unfortunately, these parameters do not solve the specific issue of network clients waiting too long to give up on a tcp connection silently terminated by an intermediary network device.

https://github.com/cloudfoundry/garden-runc-release/commit/df5a1fac409a3bfada10e2c12b098dfa72d166b8
https://github.com/cloudfoundry/guardian/commit/93f85e1b9a84023945d278d0ced156432cf47690

Using `nsenter` we were able to manually verify that lowering `tcp_retries2` allows this interval to be shortened for network clients running in guardian containers.

## Environment

* garden-runc-release version: 1.19.16
* Enabled configuration: cf
* IaaS: vSphere
* Stemcell version: 456.114
* Kernel version: 4.6

## Steps to reproduce

* deploy a guardian container containing an app that makes a long-running tcp connection over a firewall.
* forcibly terminate the firewall, causing the TCP stream to be silently broken (no messages either way)
* observe the long interval taken by the container to give up on the non-responsive tcp stream
* destroy and recreate the container
* before initiating the connection, use `nsenter` to set `/proc/sys/net/ipv4/tcp_retries2` to a number between 4 and 9 (the default from the init_net ns is 15).
* initiate the connection and kill the firewall
* notice that the application 'gives up' on the connection in a much more timely manner.

## Resolution
leverage the work in the referenced commits to allow the customization of tcp_retries1 and tcp_retries2.

**Comment by danail-branekov** [comment]
Hey @rhardt-pivotal,

Thanks for the PR, it has been merged and released in garden-runc-release 1.19.18. Closing.
