### ISSUE TITLE
Is there any way to get the container's network I/O information?

### ISSUE THREAD

**Issue by RomulusKim** [cloudfoundry/garden-runc-release#166]
## Description
Hi~
I hava a question.

If you enable the garden-external-networker, silk-cni part in the *deployment.yml file, diego-> rep will not be able to get the container's network I/O information, and if you disable it (comment), you can get the information.
Is there any way to get the container's network I/O information while active?

The red box in the image below.

![캡처](https://user-images.githubusercontent.com/73581918/100173966-e69c9080-2f0e-11eb-8622-8fcd57e2e96f.PNG)

![캡처2](https://user-images.githubusercontent.com/73581918/100173981-edc39e80-2f0e-11eb-9a9b-5b0f575c86b2.PNG)

## Environment

* garden-runc-release version: 1.19.15
* Enabled configuration: containerd, bpm, garden, diego, etc 
* IaaS: openstack
* Stemcell version: bosh-stemcell-621.78-openstack-kvm-ubuntu-xenial-go_agent.tgz
* Kernel version: 4.15.0-112-generic

**Comment by danail-branekov** [comment]
Hey @RomulusKim 

I did not quite understand what sort of network I/O information you are looking for, could you please elaborate?

I just pushed a test app on one of our test environments with the external networker enabled, and I can see that network IO stats are available under `/sys/class/net/<network device name>/statistics/`, where `network device name` is `eth0`, probably would be the same for you:

```
❯ cf ssh dora
vcap@64419a6a-069c-4984-7a1f-5625:~$ cat /sys/class/net/eth0/statistics/rx_bytes
91800
vcap@64419a6a-069c-4984-7a1f-5625:~$ cat /sys/class/net/eth0/statistics/tx_bytes
101531
```

More information on the sysfs network statistics can be found [here](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net-statistics)

Let me know whether this helps!
