### ISSUE TITLE
fork/exec /proc/self/exe: resource temporarily unavailable on bionic-stemcells

### ISSUE THREAD

**Issue by stanimir95** [cloudfoundry/garden-runc-release#168]
Hello everyone !
I've been testing bionic-stemcells on diego-cells and faced the following problem:

## Description
When testing bionic-stemcells i've encountered error similar to [thread](https://www.pivotaltracker.com/n/projects/1158420/stories/176595591)
So i've applied the proposed [fix](https://github.com/cloudfoundry/garden-runc-release/commit/8dec786a6bbe25f6ed8910e910b9799fafad1a61).
While errors seem to drastically reduce in count i'm still getting crashed instances (between 20 and 50 per 200) with the errors in the logs below 

from slack conversation:
* How did you apply the fix (keep in mind that it has not been officially released yet)
The fix was manual adding TasksMax=infinity  in /var/vcap/jobs/garden/config/garden.service and restarting the service
* Could you provide the dontpanic report from a cell that has the issue occurred?
[os-report-58ccb6d2-83ab-463a-b09d-aea87b0ab5a1-2021-02-17-12-24-51.636619703.tar.gz](https://github.com/cloudfoundry/garden-runc-release/files/5996225/os-report-58ccb6d2-83ab-463a-b09d-aea87b0ab5a1-2021-02-17-12-24-51.636619703.tar.gz)

* Could you provide the application you use to reproduce the issue?
I've attached the application [main.go.zip](https://github.com/cloudfoundry/garden-runc-release/files/5995612/main.go.zip)
* Do you manage to reproduce the issue on every cf push, or does it just happen occasionally?
Errors always show up in logs, but vary in density.
Sometimes ~50 instances of an application are crashed and logs are full of errors, sometimes ~10 and errors are very rare in logs.
* Does the 500 times of gaol run test succeed on a cell that reproduces the issue? Maybe this test is not good enough…? (edited)
gaol run always succeeded when executed, but i'm not sure if it's enough to provide a point of reference

* Do you happen yo use a boshlite deployment, or this is a “real one”?
We're using a "real one" as to be close as possible to production
* What is the underlying PAAS
Correct me if unclear: Cloudfoundry is running on Azure VMs
* How many diego cells are there in the deployment?
Currently 3 (as it's a test environment) 
* Could bosh for whatever reason have recreated the cell? In this case your manually applied fix will be gone…
No cell recreation has occurred during the testing. I'm the only one using the test environment.

`ulimit -a` on all diego-cells
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 257139
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 257139
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

## Environment

* garden-runc-release version: garden-runc/1.19.18/garden-runc-1.19.18
* IaaS: Azure
* Stemcell version: ubuntu-bionic/0.6
* Kernel version: 5.4.0-52-generic

## Steps to reproduce
running `cf push -i 200`

## Logs
`2021-02-16T09:10:09.59+0000 [CELL/186] ERR Cell 9ee9e915-62af-4f27-b25e-16851cb51486 failed to create container for instance b1744f55-df97-4634-6d3d-3f6a: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: EOF: unknown`

`
 2021-02-16T09:16:56.65+0000 [CELL/167] ERR Copying droplet into the container failed: stream-in: nstar: error streaming in: fork/exec /var/vcap/packages/guardian/bin/nstar: resource temporarily unavailable. Output:
`

`
   2021-02-15T16:00:17.09+0000 [API/0] OUT Process has crashed with type: "web"
   2021-02-15T16:00:17.11+0000 [API/0] OUT App instance exited with guid 242048d6-d506-434e-a3a5-ccc9164b8ef4 payload: {"instance"=>"afb5cf4a-2704-437b-7772-d1a
f", "index"=>36, "cell_id"=>"9ee9e915-62af-4f27-b25e-16851cb51486", "reason"=>"CRASHED", "exit_description"=>"Instance never healthy after 14.258s: 1 error occu
rred:\n\t* runc exec: exit status 1: container_linux.go:367: starting container process caused: process_linux.go:338: getting the final child's pid from pipe ca
used: EOF\n\n; 1 error occurred:\n\t* runc exec: exit status 1: container_linux.go:367: starting container process caused: process_linux.go:311: starting init p
rocess command caused: fork/exec /proc/self/exe: resource temporarily unavailable\n\n", "crash_count"=>4, "crash_timestamp"=>1613404817058533141, "version"=>"c0
fc0891-8dcd-4232-bb2e-08262fa7161a"}`

Not sure if relevant as i got the error only one time:
`
   runtime: failed to create new OS thread (have 4 already; errno=11)
   runtime: may need to increase max user processes (ulimit -u)
   fatal error: newosproc
   runtime stack:
   runtime.throw(0xc48ce7, 0x9)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/panic.go:1116 +0x72
   runtime.newosproc(0xc000052800)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/os_linux.go:161 +0x1c5
   runtime.newm1(0xc000052800)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:1843 +0xdd
   runtime.newm(0x0, 0xc000022000, 0x3)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:1822 +0x9b
   runtime.startm(0xc000022000, 0x1120f00)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:1979 +0xc9
   runtime.handoffp(0xc000022000)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:2007 +0x52
   runtime.stoplockedm()
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:2081 +0xf7
   runtime.schedule()
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:2617 +0x48c
   runtime.park_m(0xc000000180)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:2851 +0x9d
   runtime.mcall(0x0)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/asm_amd64.s:318 +0x5b
   goroutine 1 [chan receive, locked to thread]:
   runtime.gopark(0xc70490, 0xc00006e058, 0x170e, 0x2)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:306 +0xe5
   runtime.chanrecv(0xc00006e000, 0x0, 0xc000000101, 0x41a0fe)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/chan.go:577 +0x36f
   runtime.chanrecv1(0xc00006e000, 0x0)
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/chan.go:439 +0x2b
   runtime.gcenable()
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/mgc.go:219 +0x95
   runtime.main()
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/proc.go:167 +0x11e
   runtime.goexit()
   	/tmp/x86_64-linux-gnu/ports/go/1.15.8/go/src/runtime/asm_amd64.s:1374 +0x1
`

## Cause
I think a process limit has been introduced in bionic

**Comment by stanimir95** [comment]
As an addition: What value can we check to make sure the fix is working

**Comment by stanimir95** [comment]
Hello !
I'm pretty sure the problem was on my end. I've managed to make it work with 
TasksMax=infinity

**Comment by danail-branekov** [comment]
Hey @stanimir95 
Thanks a lot for the update. So no issue then? 
I thought you tried setting TasksMax to `infinity` when giving the fix a try, any idea why it did not work?
