### ISSUE TITLE
Garden goes "unhealthy" as Diego rep cell test conatiner stuck createing

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/garden-runc-release#169]
## Description
Testing with bionic stemcell.   Many of the cells failing with unhealthy which means the rep cannot create the test healthcheck "check-XXX" container

## Environment

diego-cell/b2962862-6668-4869-85e5-607e0140966c:/var/vcap/packages# ./dontpanic/bin/dontpanic
<Useful information below, please copy-paste from here>
## Date
Mon Mar 15 17:16:54 UTC 2021
## Uptime
 17:16:54 up 2 days, 20:02,  2 users,  load average: 22.61, 23.82, 22.98
## Garden Version
ad299c4dcb9621cf8d507655d41fc2db76e41fb5
## Hostname
0731e051-edcc-4c41-9541-2f1431bbfbbd
## Memory Usage
              total        used        free      shared  buff/cache   available
Mem:          32110       19555         237         172       12317       12551
Swap:         32109        1185       30924
Total:        64220       20740       31162
## Kernel Details
Linux 0731e051-edcc-4c41-9541-2f1431bbfbbd 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
## Monit Summary
The Monit daemon 5.2.5 uptime: 3h 1m

Process 'bosh-dns-adapter'          running
Process 'garden'                    running
Process 'rep'                       running
Process 'route_emitter'             running
Process 'netmon'                    running
Process 'vxlan-policy-agent'        running
Process 'silk-daemon'               running
Process 'loggr-udp-forwarder'       running
Process 'loggregator_agent'         running
Process 'loggr-forwarder-agent'     running
Process 'loggr-syslog-agent'        running
Process 'prom_scraper'              running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'mod_vms'                   running
Process 'sssd'                      running
Process 'incrond'                   running
Process 'filebeat'                  running
System 'system_localhost'           running
## Number of Open Files

>> Number of Open Files failed: timed out after 10s
## Max Number of Open Files
102400
## List of Open Files
>> List of Open Files failed: timed out after 10s
## Map of Inodes to Paths
>> Map of Inodes to Paths failed: timed out after 1m0s
## IP Tables
>> IP Tables failed: timed out after 10s
## Containerd Tasks
<Report Complete. Archive Created: /var/vcap/data/tmp/os-report-0731e051-edcc-4c41-9541-2f1431bbfbbd-2021-03-15-17-16-54.300801039.tar.gz>

## Steps to reproduce
Running in bionic stemcell

## Logs
Will provide dontpanic output in Slack

**Comment by andrew-edgar** [comment]
It still did not work after testing 1.19.20.

Here is the cut and paste of dontpanic.  I will send the gz in slack

<Useful information below, please copy-paste from here>
## Date
Wed Mar 17 22:05:18 UTC 2021
## Uptime
 22:05:18 up  4:31,  2 users,  load average: 40.46, 43.80, 46.90
## Garden Version
af39e7c43e9540444420b07183cb388ad981ebac
## Hostname
a5dd6630-60cf-4449-9efc-ad304fbe9478
## Memory Usage
              total        used        free      shared  buff/cache   available
Mem:          32110       19051         261         346       12797       12813
Swap:         32109         877       31232
Total:        64220       19928       31494
## Kernel Details
Linux a5dd6630-60cf-4449-9efc-ad304fbe9478 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
## Monit Summary
The Monit daemon 5.2.5 uptime: 4h 28m

Process 'bosh-dns-adapter'          running
Process 'garden'                    running
Process 'rep'                       running
Process 'route_emitter'             running
Process 'netmon'                    running
Process 'vxlan-policy-agent'        running
Process 'silk-daemon'               running
Process 'loggr-udp-forwarder'       running
Process 'loggregator_agent'         running
Process 'loggr-forwarder-agent'     running
Process 'loggr-syslog-agent'        running
Process 'prom_scraper'              running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'mod_vms'                   running
Process 'sssd'                      running
Process 'incrond'                   running
Process 'filebeat'                  running
System 'system_localhost'           running
## Number of Open Files







>> Number of Open Files failed: timed out after 10s
## Max Number of Open Files
102400
## Disk Usage
## GrootFS Unprivileged Usage
## GrootFS Privileged Usage
## List of Open Files
>> List of Open Files failed: timed out after 10s
## Map of Inodes to Paths
>> Map of Inodes to Paths failed: timed out after 1m0s
## Process Information
## Process Tree
## Kernel Messages
## Network Interfaces
## IP Tables
>> IP Tables failed: timed out after 10s
## NAT IP Tables
## Mount Table
## Garden Depot Contents
## XFS Fragmentation
## XFS Info
## Slabinfo
## Meminfo
## IOSTAT -xdm (slow)
## VMSTAT -s
## VMSTAT -d (slow)
## VMSTAT -a (slow)
## Mass Process Data
## Kernel Log
## Monit Log
## Syslog
## Garden Config
## Garden Logs
## Sysstat
## Garden Containers
## Containerd Init Containers
## Containerd Pea Containers
## Containerd Tasks
<Report Complete. Archive Created: /var/vcap/data/tmp/os-report-a5dd6630-60cf-4449-9efc-ad304fbe9478-2021-03-17-22-05-18.020658862.tar.gz>

**Comment by kieron-dev** [comment]
Marking this as complete. We have released garden-runc with runc-v1.0.0-rc92 avoiding the change in rc93 which triggers this bug. We have PR'ed runc with a fix to the deadlock in rc93. This has been merged and will be part of rc94. We'll cut a new garden-runc release when rc94 is released.
