### ISSUE TITLE
Garden sometimes returns huge values for `TotalUsageTowardLimit`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#170]
# Context

The `TotalUsageTowardLimit` metric is calculated using values coming from the [`memory.stat` file](https://github.com/torvalds/linux/blob/899cbb0e53c6b66c3fb98d8745aa4b0b41cd94f2/Documentation/admin-guide/cgroup-v1/memory.rst#52-stat-file) in the `memory` [cgroup](https://man7.org/linux/man-pages/man7/cgroups.7.html).

Initially, we calculated it as `total_rss` + `total_cache` - `total_inactive_file`.

We believe the subtraction of `total_inactive_file` was borrowed from Docker. They mention it in this note from the [`docker stats` docs](https://docs.docker.com/engine/reference/commandline/stats/):

> On Linux, the Docker CLI reports memory usage by subtracting cache usage from the total memory usage. The API does not perform such a calculation but rather provides the total memory usage and the amount from the cache so that clients can use the data as needed. The cache usage is defined as the value of `total_inactive_file` field in the `memory.stat` file on cgroup v1 hosts.
> On Docker 19.03 and older, the cache usage was defined as the value of `cache` field. On cgroup v2 hosts, the cache usage is defined as the value of `inactive_file` field.

As per the addition, this is what the [`usage_in_bytes` kernel docs](https://github.com/torvalds/linux/blob/899cbb0e53c6b66c3fb98d8745aa4b0b41cd94f2/Documentation/admin-guide/cgroup-v1/memory.rst#55-usage_in_bytes) say:

> For efficiency, as other kernel components, memory cgroup uses some optimization to avoid unnecessary cacheline false sharing. `usage_in_bytes` is affected by the method and doesn't show 'exact' value of memory (and swap) usage, it's a fuzz value for efficient access. (Of course, when necessary, it's synchronized.) If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP) value in `memory.stat`.

For some reason the swap value (`total_swap`) was omitted.

# Issue

A customer has reported errors when `cf push`ing caused by very large values of `TotalUsageTowardLimit`:

```
json: cannot unmarshal number 18446744073709478000 into Go struct field .stats.usage.mem of type int64
```

While one of the issues is the difference of types in the structs (`int64` vs `uint64`), the number is still clearly incorrect. We believe this is caused by an underflow in our subtraction, which leads to numbers close to the maximum `uint64` (`18446744073709551615`).

We tried to fix this by [including `total_swap`](https://github.com/cloudfoundry/guardian/commit/7cedd027cc344207d6a8e2b8bfa4a056e38c1bae) in the calculation, but even this doesn't seem to be resolutive. 

# Solution

Given the returned number is going to be incorrect anyway, until we find a better way of calculating this value we should make sure that we never underflow, and return `0` in those cases.

**Comment by gcapizzi** [comment]
Stats from a container causing the issue:
```
{
  "aff9656a-5637-43d1-5731-9777": {
    "Metrics": {
      "MemoryStat": {
        "active_anon": 40960,
        "active_file": 0,
        "cache": 0,
        "hierarchical_memory_limit": 1107296256,
        "inactive_anon": 0,
        "inactive_file": 110592,
        "mapped_file": 0,
        "pgfault": 1056,
        "pgmajfault": 0,
        "pgpgin": 792,
        "pgpgout": 775,
        "rss": 0,
        "total_active_anon": 40960,
        "total_active_file": 0,
        "total_cache": 0,
        "total_inactive_anon": 0,
        "total_inactive_file": 110592,
        "total_mapped_file": 0,
        "total_pgfault": 1056,
        "total_pgmajfault": 0,
        "total_pgpgin": 792,
        "total_pgpgout": 775,
        "total_rss": 0,
        "total_unevictable": 0,
        "unevictable": 0,
        "swap": 0,
        "hierarchical_memsw_limit": 1107296256,
        "total_swap": 0,
        "TotalUsageTowardLimit": 18446744073709440000
      },
      ...
    },
    ...
  }
}
```

**`total_rss`, `total_cache` and `total_swap` are all `0`!** We're not sure why this is happening, but we should handle this by just returning `0` instead of returning an absurd number.

**Comment by cweibel** [comment]
I know this is old, but what tool are you using to see the `MemoryStat` output?

These aren't metrics I'm see as output using the Log Cache CLI (ie: `cf tail myapp -c metrics -f`)
