### ISSUE TITLE
Document our tests

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#173]
Let's prepare a list of our test suites, and what they are for:
* Unit tests
* `gqt*`
* [GATs](https://github.com/cloudfoundry/garden-integration-tests)

Let's also mention the scripts that we use to run tests.

**Comment by georgethebeatle** [comment]
Added page: https://github.com/cloudfoundry/garden-runc-release/wiki/Testing

There are still a coulpe of TODOs
