### ISSUE TITLE
Recover the Garden Onboarding Tracker project

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#176]
Let's recover the Tracker project we used for onboarding new team members and make it easy to consume.

One idea could be to use [prolific](https://github.com/onsi/prolific) which allows to store the project as a collection of readable text files. The [cf-onboarding repository](https://github.com/pivotal/cf-onboarding) is an example.

**Comment by kieron-dev** [comment]
We've created masters-of-cats/garden-onboarding-tracker for this.

I've loaded all the stories from my tracker so far. There are some hints on some of the early stories. These need to be added somehow.
