### ISSUE TITLE
bosh.io sha1 mismatch

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/garden-runc-release#19]
Tried deploying garden-runc-release from bosh.io but getting sha1 mismatches:

```
Checking whether release garden-runc/1.0.0 already exists...NO
Using remote release 'https://bosh.io/d/github.com/cloudfoundry-incubator/garden-runc-release?v=1.0.0'

Director task 42532
  Started downloading remote release > Downloading remote release. Done (00:00:09)

  Started verifying remote release > Verifying remote release. Failed: Release SHA1 `41a9407af7eaa412a6a2dca2cbf29f2623d4e12f' does not match the expected SHA1 `2f29b4d9eedbe6b79efe3703b68a4d3c785649f4' (00:00:01)

Error 30015: Release SHA1 `41a9407af7eaa412a6a2dca2cbf29f2623d4e12f' does not match the expected SHA1 `2f29b4d9eedbe6b79efe3703b68a4d3c785649f4'
```

Issue with release or https://bosh.io/releases/github.com/cloudfoundry/garden-runc-release?version=1.0.0 or am I doing something wrong?

/cc @julz @cppforlife

**Comment by cppforlife** [comment]
not sure where 2f2.. came from but expected sha1 matches (https://bosh.io/releases/github.com/cloudfoundry-incubator/garden-runc-release?all=1)

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#132637741](https://www.pivotaltracker.com/story/show/132637741) bosh.io sha1 mismatch


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by drnic** [comment]
Ok, glad its resolved itself.

Screenshot of what I saw early:
![screen shot 2016-10-18 at 2 23 46 pm](https://cloud.githubusercontent.com/assets/108/19463297/89bc04ae-953e-11e6-8ea7-2753fc1af200.png)

**Comment by cppforlife** [comment]
note that two are different orgs: cloudfoundry vs cloudfoundry-incubator
