### ISSUE TITLE
Investigate performance regression on Bionic stemcell

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#190]
It looks like Bionic makes our container creations twice as slow. See [this graph](https://longboard.wavefront.com/dashboards/Garden-CI-Monitor#_v01(g:(d:2419200,ls:!t,s:1620741178,w:'4w'),l:(Garden-CI-Monitor-1-1-1:(d:130683,s:1621890908)))) on Wavefront. Let's find out why.

**Comment by gcapizzi** [comment]
@MarcPaquette not sure about the issue - it might depend more on the environment we're using than the code itself, as I see the graph creeping up and then dropping every once in a while. 

Re: dashboard access, anyone who wants it should create a Wavefront account and then we can add them!

**Comment by MarcPaquette** [comment]
After some discussion with the Garden team, this issue doesn't appear to be occurring anymore with high versions of the Bionic stemcells.

A follow up to create wavefront accounts for the Runtime for WaveFront.
