### ISSUE TITLE
bump concourse deployment to v7.4.0

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/garden-runc-release#192]
Our CI is currently on v7.2.0

**Comment by mnitchev** [comment]
While doing this bump we also encountered problems in our tests, caused by the switch from xenial to a bionic stemcell in [concourse-bosh-deployment](https://github.com/concourse/concourse-bosh-deployment/commit/7c6abae254e39da0377ee267b2decd20dfb4211a). We created #189 to solve this.

**Comment by mnitchev** [comment]
After removing the garden-runc-release from the windows job (in garden-ci) that was hanging, we hit a pid limit on the linux workers which caused random jobs to fail. We submitted [a PR](https://github.com/concourse/concourse-bosh-release/pull/153) to fix this in concourse-bosh-release

**Comment by georgethebeatle** [comment]
We introduced a temporary workaround by deploying a local concourse version with the fix from the above PR applied on top of v7.3.1. When there is a proper fix the following commit should be reverted:

https://github.com/cloudfoundry/garden-ci/commit/7d1681f21a2f7b92d3920a023fa4636818b1065d

**Comment by gcapizzi** [comment]
PR is going to be part of 7.4.0, blocking on that.

**Comment by georgethebeatle** [comment]
concourse v7.4.0 is out, unblocking
