### ISSUE TITLE
Increased instance memory consumption after migration to a bigger cell VM type.

### ISSUE THREAD

**Issue by PlamenDoychev** [cloudfoundry/garden-runc-release#193]
## Description

Hi Garden Colleagues,
We noticed after diego cells VM type migration increased application instance memory consumption. We scaled cells VMs from 128 GB to 256 GB memory and end up in situation with thousands of failing apps with OOM exception.
This behaviour applies for any type of applications, tests were performed with golang, nodeJS, Java, php and ruby based applications and observed increased consumption is a few MiB. 
We have received confirmation from IaaS provider that both VM types are build on top of one and the same architecture and the only difference between them is number of vCPUs and Memory. 

## Environment

* garden-runc-release version: 1.19.28
* IaaS: AWS
* Stemcell version: bosh-aws-xen-hvm-ubuntu-bionic-go_agent/1.10
* Kernel version: 5.4.0-74-generic

## Steps to reproduce
Deploy dummy app on 128 GB cell migrate to 256 GB cell and monitor applications instance memory consumption. Something  similar to the example below should be observed.

```
128 GB cell
type:     web
sidecars:    
instances:   1/1
memory usage: 750M
    state    since          cpu   memory      disk       details
#0 running 2021-06-23T09:55:54Z 0.6%  93.7M of 750M  118.7M of 1G 
 
256 GB cell
type:       web
sidecars:    
instances:    1/1
memory usage:   750M
    state    since          cpu   memory      disk       details
#0   running   2021-06-23T09:11:21Z   4.1%   100M of 750M   118.7M of 1G 
```

## Kernel logs

```
Jun 25, 2021 @ 12:42:13.029 | kernel | [113782.638786] Memory cgroup out of memory: Killed process 1949510 (envoy) total-vm:3264844kB, anon-rss:18812kB, file-rss:30452kB, shmem-rss:4kB, UID:4294967294 pgtables:732kB oom_score_adj:0
-- | -- | --

  | Jun 25, 2021 @ 12:42:12.104 | kernel | [115582.355745] Memory cgroup stats for /system.slice/garden.service/garden/good/db315859-a870-4d77-50f9-02b6:

  | Jun 25, 2021 @ 12:42:11.916 | kernel | [115559.166744] Memory cgroup out of memory: Killed process 2009943 (envoy) total-vm:3264844kB, anon-rss:19012kB, file-rss:30712kB, shmem-rss:4kB, UID:4294967294 pgtables:740kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:11.482 | kernel | [114632.849111] Memory cgroup out of memory: Killed process 2856839 (envoy) total-vm:3264844kB, anon-rss:19840kB, file-rss:30904kB, shmem-rss:4kB, UID:4294967294 pgtables:724kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:11.411 | kernel | [118780.207003] Memory cgroup stats for /system.slice/garden.service/garden/good/88687739-ff79-4e0c-79d0-d231:

  | Jun 25, 2021 @ 12:42:10.828 | kernel | [115558.078629] Memory cgroup out of memory: Killed process 1948188 (envoy) total-vm:3264844kB, anon-rss:18908kB, file-rss:30932kB, shmem-rss:4kB, UID:4294967294 pgtables:724kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:09.765 | kernel | [119882.126972] Memory cgroup stats for /system.slice/garden.service/garden/good/ec2c1054-d779-43b2-749c-ddd4:

  | Jun 25, 2021 @ 12:42:09.666 | kernel | [115542.020010] Memory cgroup stats for /system.slice/garden.service/garden/good/da5b7375-3529-4a3a-7c7c-f8fe:

  | Jun 25, 2021 @ 12:42:09.373 | kernel | [118812.605175] Memory cgroup stats for /system.slice/garden.service/garden/good/cad600d4-2dd6-49fe-4a10-b559:

  | Jun 25, 2021 @ 12:42:09.365 | kernel | [117697.402151] Memory cgroup stats for /system.slice/garden.service/garden/good/ece24187-bdf6-497a-7697-55c4:

  | Jun 25, 2021 @ 12:42:09.354 | kernel | [118777.895227] Memory cgroup out of memory: Killed process 652703 (envoy) total-vm:3264844kB, anon-rss:19120kB, file-rss:30532kB, shmem-rss:4kB, UID:4294967294 pgtables:724kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:09.354 | kernel | [118777.894633] Memory cgroup stats for /system.slice/garden.service/garden/good/4f154427-16f1-42f2-647a-15d6:

  | Jun 25, 2021 @ 12:42:09.275 | kernel | [113659.176275] Memory cgroup stats for /system.slice/garden.service/garden/good/50c5ba2d-87f3-4f77-4912-3219:

  | Jun 25, 2021 @ 12:42:09.127 | kernel | [113697.493385] Memory cgroup out of memory: Killed process 3201357 (envoy) total-vm:3264844kB, anon-rss:19408kB, file-rss:30840kB, shmem-rss:4kB, UID:4294967294 pgtables:728kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:09.064 | kernel | [119873.050322] Memory cgroup stats for /system.slice/garden.service/garden/good/1f05f290-065a-4862-5529-80b2:

  | Jun 25, 2021 @ 12:42:09.064 | kernel | [119873.050980] Memory cgroup out of memory: Killed process 4159318 (envoy) total-vm:3264844kB, anon-rss:19128kB, file-rss:30644kB, shmem-rss:4kB, UID:4294967294 pgtables:804kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.908 | kernel | [113697.274023] Memory cgroup out of memory: Killed process 3134304 (envoy) total-vm:3264972kB, anon-rss:19128kB, file-rss:30740kB, shmem-rss:4kB, UID:4294967294 pgtables:728kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.908 | kernel | [113697.273337] Memory cgroup stats for /system.slice/garden.service/garden/good/876f862e-4c85-40d1-42ef-4375:

  | Jun 25, 2021 @ 12:42:08.717 | kernel | [113740.935768] Memory cgroup stats for /system.slice/garden.service/garden/good/50c5aa2d-689e-4340-5c5e-1010:

  | Jun 25, 2021 @ 12:42:08.600 | kernel | [115569.066205] Memory cgroup out of memory: Killed process 1097954 (envoy) total-vm:3264844kB, anon-rss:18928kB, file-rss:30696kB, shmem-rss:4kB, UID:4294967294 pgtables:808kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.577 | kernel | [114613.335163] Memory cgroup stats for /system.slice/garden.service/garden/good/f8e148d2-4920-4122-40de-2720:

  | Jun 25, 2021 @ 12:42:08.577 | kernel | [114613.335773] Memory cgroup out of memory: Killed process 2148966 (envoy) total-vm:3264844kB, anon-rss:19368kB, file-rss:30708kB, shmem-rss:4kB, UID:4294967294 pgtables:728kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.539 | kernel | [114613.293750] Memory cgroup out of memory: Killed process 2224562 (envoy) total-vm:3264844kB, anon-rss:18788kB, file-rss:30756kB, shmem-rss:4kB, UID:4294967294 pgtables:724kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.539 | kernel | [114613.293157] Memory cgroup stats for /system.slice/garden.service/garden/good/a54897a0-3e17-4d9b-4d65-02e9:

  | Jun 25, 2021 @ 12:42:08.459 | kernel | [115547.107117] Memory cgroup out of memory: Killed process 1110454 (envoy) total-vm:3264844kB, anon-rss:18936kB, file-rss:30808kB, shmem-rss:4kB, UID:4294967294 pgtables:808kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.414 | kernel | [116051.512967] Memory cgroup stats for /system.slice/garden.service/garden/good/c856c920-0c86-4dfc-7cc7-f879:

  | Jun 25, 2021 @ 12:42:08.276 | kernel | [114608.817382] Memory cgroup out of memory: Killed process 2204495 (envoy) total-vm:3264844kB, anon-rss:18796kB, file-rss:30756kB, shmem-rss:4kB, UID:4294967294 pgtables:808kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.274 | kernel | [113753.065006] Memory cgroup out of memory: Killed process 2491749 (envoy) total-vm:3264844kB, anon-rss:19128kB, file-rss:30500kB, shmem-rss:4kB, UID:4294967294 pgtables:796kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.221 | kernel | [117628.096501] Memory cgroup out of memory: Killed process 2727308 (envoy) total-vm:3264844kB, anon-rss:18812kB, file-rss:30540kB, shmem-rss:4kB, UID:4294967294 pgtables:732kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.171 | kernel | [117683.895572] Memory cgroup out of memory: Killed process 3696570 (envoy) total-vm:3264844kB, anon-rss:18996kB, file-rss:30692kB, shmem-rss:4kB, UID:4294967294 pgtables:812kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.148 | kernel | [115552.099146] Memory cgroup out of memory: Killed process 1372142 (envoy) total-vm:3264844kB, anon-rss:19692kB, file-rss:30764kB, shmem-rss:4kB, UID:4294967294 pgtables:724kB oom_score_adj:0

  | Jun 25, 2021 @ 12:42:08.092 | kernel | [114700.011797] Memory cgroup out of memory: Killed process 3669709 (envoy) total-vm:3264844kB, anon-rss:19896kB, file-rss:30820kB, shmem-rss:4kB, UID:4294967294 pgtables:728kB oom_score_adj:0

```

## Don't panic logs

```
## Date
Fri Jun 25 10:35:42 UTC 2021
## Uptime
 10:35:42 up 1 day,  7:01,  2 users,  load average: 5.12, 4.63, 4.24
## Garden Version
2f945c09a983e47325c314bf1237c31fe5acda62
## Hostname
87cedfff-828f-468f-bbd2-b137c12a3a2a
## Memory Usage
              total        used        free      shared  buff/cache   available
Mem:         254999       44620      110722         387       99656      210257
Swap:          8191           0        8191
Total:       263191       44620      118914
## Kernel Details
Linux 87cedfff-828f-468f-bbd2-b137c12a3a2a 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
## Monit Summary
The Monit daemon 5.2.5 uptime: 1d 6h 59m

Process 'bosh-dns-adapter'          running
Process 'garden'                    running
Process 'rep'                       running
Process 'route_emitter'             running
Process 'netmon'                    running
Process 'vxlan-policy-agent'        running
Process 'silk-daemon'               running
Process 'loggr-udp-forwarder'       running
Process 'fssnfsdriver'              running
Process 'loggregator_agent'         running
Process 'loggr-forwarder-agent'     running
Process 'loggr-syslog-agent'        running
Process 'prom_scraper'              running
Process 'metrics-discovery-registrar' running
Process 'metrics-agent'             running
Process 'blackbox'                  running
Process 'turbulence_agent'          running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'telegraf-bosh-team'        running
System 'system_localhost'           running
## Number of Open Files

```

**Comment by danail-branekov** [comment]
Hey @PlamenDoychev 

Thanks for reporting that. `dontpanic` eventually is expected to complete (might take several minutes though) and produce an archive with debug data we are interested into. Could you provide that archive from both samller and bigger cells?

**Comment by PlamenDoychev** [comment]
Hi @danail-branekov, 
I was waiting for more than 10 minutes dontpanic to complete and I thought that something is wrong with the tool. 
I shall give it another try i see if i get some result.
With regards to the smaller VMs, unfortunately i shall not be able to provide dumps because VMs are already released to IaaS provider and we are completely on bigger ones.

**Comment by PlamenDoychev** [comment]
Hi @danail-branekov 
After one hour waiting the tool did not manage to complete successfully. The following are the logs the tool provided:

<Useful information below, please copy-paste from here>
## Date
Mon Jun 28 06:19:08 UTC 2021
## Uptime
 06:19:08 up 4 days,  2:18,  1 user,  load average: 12.13, 18.62, 16.11
## Garden Version
2f945c09a983e47325c314bf1237c31fe5acda62
## Hostname
e2530d86-9e30-490d-849c-4111297c2694
## Memory Usage
              total        used        free      shared  buff/cache   available
Mem:         252311       81301        2229        4245      168780      168099
Swap:          8191          61        8130
Total:       260503       81362       10360
## Kernel Details
Linux e2530d86-9e30-490d-849c-4111297c2694 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
## Monit Summary
The Monit daemon 5.2.5 uptime: 4d 2h 13m

Process 'bosh-dns-adapter'          running
Process 'garden'                    running
Process 'rep'                       running
Process 'route_emitter'             running
Process 'netmon'                    running
Process 'vxlan-policy-agent'        running
Process 'silk-daemon'               running
Process 'loggr-udp-forwarder'       running
Process 'fssnfsdriver'              running
Process 'loggregator_agent'         running
Process 'loggr-forwarder-agent'     running
Process 'loggr-syslog-agent'        running
Process 'prom_scraper'              running
Process 'metrics-discovery-registrar' running
Process 'metrics-agent'             running
Process 'blackbox'                  running
Process 'turbulence_agent'          running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'telegraf-bosh-team'        running
System 'system_localhost'           running
## Number of Open Files
>> Number of Open Files failed: timed out after 10s
## Max Number of Open Files
25802520
## Disk Usage
## GrootFS Unprivileged Usage

**Comment by StefanWutz** [comment]
Having a look also on this issue we see that the envoy proxy sidecar is creating a lot of worker threads based on the hardware threads available on the vm.

The problem is that this setting is not configured by diego-release[1] and envoy resorts to its default behavior[2].

For example, on AWS we see an increase of worker threads depending on the instance type:

```
m5.8xlarge: 70 threads per envoy instance
m5.16xlarge: 134 threads per envoy instance
```

[1] https://github.com/cloudfoundry/executor/blob/master/depot/transformer/transformer.go#L737
[2] https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-concurrency

**Comment by georgethebeatle** [comment]
Unfortunately there is no easy thing we can do in garden to mitigate this problem. All garden controls is how much memory is allowed as an upper limit in the container - this is configurable on the app level and is reflected in the final bill of the app. Diego propagates that value to Garden via the [container spec](https://github.com/cloudfoundry/guardian/blob/2cab4bbdfcc3ecf9032f6299d3ff5881d5f31043/vendor/code.cloudfoundry.org/garden/client.go#L148), then Garden [sets it](https://github.com/cloudfoundry/guardian/blob/2cab4bbdfcc3ecf9032f6299d3ff5881d5f31043/rundmc/bundlerules/limits.go#L21-L28) in the runc spec as is an it ends up in the respective cgroup. 

As @StefanWutz pointed out above the envoy args (`--concurrency` in particular) is controlled by diego and depends directly on the size of the underlying VM instance. For a sufficiently large VM type envoy will spawn enough threads to exceed the memory limits the user is paying for. So if there is to be a fix it should be done in Diego.

That said fixing it would not be trivial in diego either, because
- It would be tricky to determine an envoy concurrency value that will work for all apps. Apps with more traffic would need more envoy workers than apps with less traffic. If diego limits envoy to 1 worker this issue will go away, but network performance might degrade.
- The VM size is decided by the operator and the app memory limit is decided by the app deployer. Both an operator decision to scale up and an app deployer decision to scale down (in terms of memory) will lead to this problem regardless of the chosen value of envoy concurrency

The simplest fix if this occurs is that all crashing apps are scaled up, since they are suddenly consuming more memory (even though it goes to the sidecar). On the other hand it does not feel right for an app to pay more because of an operator's decision to use larger VMs.

So, **TL;DR** this looks more like a diego issue, but also a tricky one to solve.

**Comment by yatzek** [comment]
Yes, this looks like a diego issue. What would probably make sense is to expose a diego deployment property for envoy concurrency and default it to a sensible value (not sure what should that be, up for a discussion: https://github.com/projectcontour/contour/issues/2929). This way operators would be able to fine tune it depending on the size of the diego cell.
