### ISSUE TITLE
Refresh CI Bosh Director certs

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/garden-runc-release#200]
eden certs have expired again.

**Comment by kieron-dev** [comment]
We deleted all the certs from eden/bosh-init/creds.yml and ran ./deploy.sh. This failed with a TLS handshake error while downloading the stemcell locally. So we changed the stemcell URL to a local file in the bosh-deployment/gcp/cpi.yml. That allowed it to progress.

**Comment by kieron-dev** [comment]
We noticed that bumping bosh CLI to 6.4.4 would have fixed the problem above.

Anyway, the bosh director was successfully recreated with new certs. Then all deployments had unreachable agents, so we scripted `bosh cck` to recreate them all:

```
bosh ds | awk '/^[^ ]/ {print $1}' | xargs -I N sh -c 'echo "3\ny" | bosh -d N  cck &'
```

This didn't work for concourse as it assumes just one vm in the deployment. So we did concourse manually: `bosh -d concourse cck`.

We replaced the bosh CA in the CI gcp.yml, and reconfigured the pipeline to fix some resource getting issues. CI is still red in places, so we'll fix that step by step.

**Comment by kieron-dev** [comment]
Only problem was boshlite-latest-grr-gats which was waiting for us to push the new certs to the CI repo.

**Comment by MarcPaquette** [comment]
Hi @kieron-dev,

Is this issue all set? Any further actions needed or is it safe to close out?

Thanks,
@MarcPaquette

**Comment by kieron-dev** [comment]
Hi @MarcPaquette 

Yes this is complete. Not sure why I missed closing it.
