### ISSUE TITLE
Garden might fail to generate the bundle when mounts from an SMB volume are present

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#204]
When generating the [mounts](https://github.com/opencontainers/runtime-spec/blob/master/config.md#mounts) section of the OCI bundle (via [`bundlerules.Mounts`](https://github.com/cloudfoundry/guardian/blob/ca12a3a918ed36c17ee8a459a3b065987456014c/rundmc/bundlerules/mounts.go)), Garden needs to propagate the mount flags used to mount the volume containing the `source` path (see the [Tracker story](https://www.pivotaltracker.com/n/projects/1158420/stories/160551863) introducing this behaviour).

Garden does this using [this code](https://github.com/cloudfoundry/guardian/blob/ca12a3a918ed36c17ee8a459a3b065987456014c/rundmc/bundlerules/mount_options_linux.go) we copied from [Docker/Moby](https://github.com/moby/moby/blob/ba2adeebdb8d4ec442f1d3107405ae55d0c1a0c2/daemon/oci_linux.go#L424-L454). The code performs a [`statfs`](https://man7.org/linux/man-pages/man2/statfs.2.html) call and then extracts the flags that need to be propagated from the result.

Some [SMB](https://en.wikipedia.org/wiki/Server_Message_Block) users have reported `statfs` failures with `permission denied` on the latest Xenial stemcell in cases where the users don't have enough permissions on the _parent_ volume. This used to work on previous stemcells as `statfs` would not fail but just return an empty response.

We believe the best way to solve the issue for these users is to tolerate `statfs` failures in `bundlerules.Mounts`, and proceed with an empty set of flags. Sometimes this could lead to failures in creating the container, as the kernel might reject mounts that don't inherit mount options correctly, so **we still want to log the error** as a warning to make debugging of these cases easier.

**Comment by kieron-dev** [comment]
The code now panics when statfs fails.

Repro steps:
1. Use containerd-garden bosh deployment, for example
2. Install samba, smbclient and cifs-utils: `sudo apt install samba smbclient cifs-utils`
3. Create a location to serve the smb files from: `mkdir -p /home/samba/sambamount`
4. Configure samba server by adding this to the end of `/etc/samba/smb.conf`
```
[sambashare]
  comment = SMB on Ubuntu
  path = /home/samba/sambashare
  read only = no
  browsable = yes
```
5. Restart the service: `sudo service smbd restart`
6. Create a samba user (must be a name from /etc/passwd): `sudo smbpasswd -a kbrowne`
7. Create an accessible mount location: `mkdir /var/vcap/data/sambamount`
8. Set all permissions: `sudo chmod 777 /var/vcap/data/sambamount`
9. Mount the smb share there: `mount -t cifs -o username=kbrowne //localhost/sambashare /var/vcap/data/sambamount`
10. Check you can bind mount that into a container: `gaol create -n cake -m /var/vcap/data/sambamount/:/foo`
11. Muck up the parent directory permissions: `sudo chmod -x /home/samba/sambashare`
12. See that gaol create causes a panic: `gaol create -n brioche -m /var/vcap/data/sambamount/:/foo`
```
error: Post http://api/containers: EOF
```
