### ISSUE TITLE
Bump Go to v1.17

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#205]
I recovered this procedure from [Tracker](https://www.pivotaltracker.com/story/show/177182714).

First we need to make sure that all our CI tests pass with the new Go version. To do this, we first build a temporary CI image with the new Go version, update CI to use it and make sure everything passes. If this is the case, we make the new image permanent by tagging it, pushing it and setting it as our new CI image. Here's the steps:

- [x] Upgrade workstations to the new version of Go
- [x] Bump Go in the [`garden-dockerfiles/garden-ci` image](https://github.com/cloudfoundry/garden-dockerfiles/tree/master/garden-ci) by modifying the `Dockerfile` and then running `make garden-ci` (don't `git push` yet)
- [x] Verify (using `docker run`) that the version of Go is bumped
- [x] Push the new image (as the tag `latest`)
- [x] Modify the `cfgarden/garden-ci` tag in [`ci-image.yml`](https://github.com/cloudfoundry/garden-ci/blob/master/ci/pipelines/common/ci-image.yml) to `latest` and reconfigure the CI pipeline
   - Warning: that would cause all subsequent CI tasks to use the latest image, which could potentially introduce certain inconvenience for fellow gardeners
- [x] Confirm tests pass with `garden-runc-release/script/test -a` (if it fails, fix that)
- [x] Tag the new image with a patch bump
- [x] Push the change to [`garden-dockerfiles`](https://github.com/cloudfoundry/garden-dockerfiles), referencing the tag in the commit message
- [x] Modify the `cfgarden/garden-ci` tag in [`ci-image.yml`](https://github.com/cloudfoundry/garden-ci/blob/master/ci/pipelines/common/ci-image.yml) to the `cfgarden\garden-ci` tag above and reconfigure the pipeline
- [x] Push the changes to [`garden-ci`](https://github.com/cloudfoundry/garden-ci)

At this point we can bump Go in our BOSH release:

- [x] Download the new blob and run `bosh add-blob` to add the new blob to the release
- [x] Update the [`spec` and `packaging` scripts](https://github.com/cloudfoundry/garden-runc-release/tree/develop/packages/golang) to reference the new blob
- [x] Run `bosh upload-blobs` to upload the new blob
- [x] Remove the **old** blob from [`config/blobs.yml`](https://github.com/cloudfoundry/garden-runc-release/blob/develop/config/blobs.yml). Do **not** remove the old blob from S3, old revisions still need to be buildable.
- [x] Test the new package by deploying a dev release to `bosh-lite` **and/or** to a Windows machine
- [x] If everything deploys successfully, commit and push the changes
- [x] Make sure to bump the Go version on the Concourse Windows worker. In [`garden-windows-tools-release`](https://github.com/masters-of-cats/garden-windows-tools-release) follow the [README](https://github.com/masters-of-cats/garden-windows-tools-release/blob/master/README.md), bump the golang version and make a new BOSH release version
- [x] Update the concourse deployment [ops file](https://github.com/cloudfoundry/garden-ci/blob/master/directors/eden/deployments/concourse/operations/windows_tools.yml) to reference the new garden-windows-tools-release
- [x] Redeploy concourse

By following the above steps we guarantee that our package versions are in sync across BOSH releases and CI images.

**Comment by gcapizzi** [comment]
Blocking on [`bosh-packages/golang-release`](https://github.com/bosh-packages/golang-release) adding v1.17, which is a prerequisite to [`windows-tools-release`](https://github.com/cloudfoundry/windows-tools-release) adding v1.17.

**Comment by kieron-dev** [comment]
Unblocking as we now have masters-of-cats/garden-windows-tools-release

**Comment by MarcPaquette** [comment]
This story is completed. 

I also updated the[ template golang bump story](https://www.pivotaltracker.com/story/show/166953417) to reflect changes stated by @danail-branekov
