### ISSUE TITLE
Replace `windows-tools-release` with our own private release

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/garden-runc-release#206]
When we bump golang, we need to run concourse CI in linux and windows before releasing.

For linux, we bump golang in the garden-ci container image.  But concourse windows workers do not use containers, and golang must be installed on the worker via a bosh release. We currently use windows-tools-release, and install the golang-1-windows job, which installs the go for us.

The problem is that windows-tools-release usually need a nudge to create a new release. And further, they depend upon a bosh-golang-tools (I think) release which they need to vendor. So it can take days or weeks to get a new release with a recent golang.

Instead, we should have our own release that we can use to put the appropriate golang version into concourse.

Deliverables:
- [x] Bosh release in a new masters-of-cats repo
- [x] Scripts or CI to manage the release process
- [x] Update concourse to use golang from the new bosh release

**Comment by MarcPaquette** [comment]
Hi @kieron-dev,

Is this issue still open? I'm seeing some commits, but just wanted to make sure it's good before closing it out.

Thanks,
@MarcPaquette

**Comment by kieron-dev** [comment]
Hi @MarcPaquette

Again, this is done. It should be closed.

The pattern I'm seeing here is that the issue was moved to Finished on the board, which for a story would mean it was ready for approval. But it was a chore and should have gone straight to Accepted and closed.
