### ISSUE TITLE
Get the protobuf duplicate fix registration warning/panic fixed in log-cache-release

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/garden-runc-release#209]
We have provided a fix in go-cache-release in order to enable the CF CLI to stop [pinning protobuf]( https://github.com/cloudfoundry/cli/blob/19278c3aed08aa3ce867c02467be7e453c5c1c56/go.mod#L73). The same fix will work for log-cache-release, and will enable us to remove the ldflag from the [cpu entitlement plugin](https://github.com/cloudfoundry/cpu-entitlement-plugin/blob/b80848a07b7137081964b820aacb746f5624bd17/Makefile#L10).

This also affects the cpu-entitlement-admin-plugin.

**Comment by MarcPaquette** [comment]
Runtime Tracker story has been created for this issue: https://www.pivotaltracker.com/story/show/180812108

**Comment by MarcPaquette** [comment]
Hey @ebroberson,
What are your thoughts on this change?

Thanks

**Comment by ebroberson** [comment]
`cpu-entitlement-plugin` has been deprecated, and it looks like protobuf is no longer pinned in `main`.  Closing.
