### ISSUE TITLE
GrootFS additional metrics

### ISSUE THREAD

**Issue by klapkov** [cloudfoundry/garden-runc-release#210]
## Description
While debugging why the grootfs gc was not triggered I dug into the code base of the grootfs clean command. There I found that to trigger the execution of the garbage collector a certain  statement must be False. Thus to know why it hasn't been triggered I started looking at the parameters of the predicate. I was missing the usedVolumeSize metric thus I was unsure of whether grootfs had been functioning properly. Another metric that could've been useful is the usedBackingStoreInBytes which doesn't exist. Also I could've benefited of a debug log with all of the parameters used in the inequality because grootfs clean could easily be run in a debug log-level mode as a command.

## Environment

* garden-runc-release version: 1.19.31

## Resolution
 In my opinion, adding these two metrics would be very useful for debugging. Do you guys agree ? Here is a link to my fork of garden-runc: https://github.com/klapkov/garden-runc-release. Thank you for the time.

**Comment by klapkov** [comment]
Do you guys want to address this internally or are you open to contributions ?

**Comment by MarcPaquette** [comment]
Hi @klapkov,

We're continuing to review this issue at this time and we are open to contributions.

Apologies for the delay, we're transitioning this project to a different group of engineers. The delays are a result of this transition. Thanks for your patience. This issue is at the top of the list.

**Comment by MarcPaquette** [comment]
Hi @klapkov 

@ameowlia, @reneighbor and I reviewed your Groot branch. It looks great and we're looking forward to getting a Pull Request(PR) from you.

Two small bit of feedback:
- If you could squash your commits before the PR, it makes reviewing codes changes much easier for us. 
- When you make your PR, please make it against the [GrootFS repo](https://github.com/cloudfoundry/grootfs/) and we'll bump the submodules in the [garden-runc-release](https://github.com/cloudfoundry/garden-runc-release/).

Thanks again for your [contribution!](https://github.com/cloudfoundry/grootfs/blob/master/CONTRIBUTING.md) We're looking forward to getting it merged into `main`!

Thanks,
The Garden Team

**Comment by klapkov** [comment]
Hi @MarcPaquette 

Thanks for the tips on the PR. I will probably send it tomorrow.  I am glad i could help. 

Kind Regards, 
Konstantin Lapkov

**Comment by MarcPaquette** [comment]
This Issue is related to this PR: https://github.com/cloudfoundry/grootfs/pull/155

**Comment by MarcPaquette** [comment]
An internal tracking story has been created for this issue here: https://www.pivotaltracker.com/story/show/180559618

**Comment by MarcPaquette** [comment]
Closed with PR https://github.com/cloudfoundry/grootfs/pull/155
