### ISSUE TITLE
Add support in CFAR for per-docker-app seccomp profiles

### ISSUE THREAD

**Issue by chefhoobajoob** [cloudfoundry/garden-runc-release#219]
## Description

Not sure if this is the right project to post this, but we have custom docker images for which we have a requirement to run chrome in sandbox mode. We are able to do this on a vanilla k8s deployment, but we are unable to do this in CFAR because the default seccomp profile used when docker apps are launched does not make [the necessary api functions](https://github.com/tkp1n/chromium-ci/blob/master/seccomp/chromium.json) callable from the container, and as far as we can tell, there is no way to configure a custom seccomp profile per app.

This request is to make it possible to configure these profiles on a per-app basis, or at least for platform ops teams to customize this for docker app deployments.
## Environment

* garden-runc-release version: 
* Enabled configuration: 
* IaaS:
* Stemcell version: 
* Kernel version: 

## Steps to reproduce

attempt to launch crome from a CFAR docker app

**Comment by MarcPaquette** [comment]
Hi @chefhoobajoob, 
We'll work on gettting this assigned to a team member. Thanks for your patience so far!

**Comment by MarcPaquette** [comment]
Hi @chefhoobajoob,

We spoke about this issue as a team. We're not interested in pursuing the issue as stated at this time, but think there is a path forward. 

We have concerns regarding security issues that may arise when a misconfigured container may impact other apps/tasks on the platform. One bad app configuration could compromise the entire platform.  Our philosophy is to enforce the strongest security possible. 

In addition, the proposed changes would be far reaching. Changes to accommodate this request would need to occur with the following:
- cf cli
- CAPI
- Diego
- Garden

A possible middle road of adding additional seccomp permissions to Garden-runc-release manifest coupled with [isolation segments](https://docs.cloudfoundry.org/adminguide/isolation-segments.html). This would still be very much a "At One's Own Risk" type of configuration.  A PR like that would be something our team would be interested in reviewing.

Thanks,
@MarcPaquette & the Application Runtime Platform WG

**Comment by chefhoobajoob** [comment]
Ok - thank you very much for the consideration the team put into the request. Do you think a new issue would be required for the middle road approach?

**Comment by MarcPaquette** [comment]
@chefhoobajoob, 
I think if your Pull Request references this issue that would be sufficient.

Thanks!

**Comment by MarcPaquette** [comment]
Hi @chefhoobajoob, 
I'm going to close out this issue. Once you make the PR, please link this issue in it.

Thanks,
Marc
