### ISSUE TITLE
Question: now the app container started by garden, the PID 1 process is app process?

### ISSUE THREAD

**Issue by fisherxu** [cloudfoundry/garden-runc-release#226]
## Description

I remembered several years ago, warden and garden will start a process called `wshd` as init process in container, seems that now it has been removed and use the app process directly? Thanks. 

## Environment

* garden-runc-release version: 
* Enabled configuration: 
* IaaS:
* Stemcell version: 
* Kernel version:

**Comment by MarcPaquette** [comment]
Hi @fisherxu,

Right now PID 1 is the `garden-init` process. 
```
$ cf ssh dora
vcap@11b0b9b8-aba7-4fd2-7fba-caf5:~$ ps fax
    PID TTY      STAT   TIME COMMAND
     94 ?        Ssl    0:00 /etc/cf-assets/healthcheck/healthcheck -port=8080 -timeout=1000ms -liveness-interval=30s
     44 ?        Ss     0:00 sh -c trap 'kill -9 0' TERM; /etc/cf-assets/envoy/envoy -c /etc/cf-assets/envoy_config/envoy.yaml --drain-time-s 900 --log-level critical& pid=$!; wait $pid
     78 ?        Sl     0:02  \_ /etc/cf-assets/envoy/envoy -c /etc/cf-assets/envoy_config/envoy.yaml --drain-time-s 900 --log-level critical
     19 ?        Ssl    0:00 /tmp/lifecycle/diego-sshd --allowedKeyExchanges= --address=0.0.0.0:2222 --allowUnauthenticatedClients=false --inheritDaemonEnv=true --allowedCiphers= --allowedMACs= --logLevel=fatal --debugAddr=
    204 pts/0    Ss     0:00  \_ /bin/bash
    214 pts/0    R+     0:00      \_ ps fax
     14 ?        Ss     0:00 /home/vcap/deps/0/vendor_bundle/ruby/2.7.0/bin/rackup config.ru -p 8080 -o 0.0.0.0
      1 ?        Ss     0:00 /tmp/garden-init
```

The [process](https://github.com/cloudfoundry/guardian/blob/472ba1e64faf7e75d60d17b4d28a2143a750c4a1/guardiancmd/command_linux.go#L189) is [created](https://github.com/cloudfoundry/guardian/blob/472ba1e64faf7e75d60d17b4d28a2143a750c4a1/guardiancmd/command.go#L498), then passed onto [containerd](https://github.com/cloudfoundry/guardian/blob/472ba1e64faf7e75d60d17b4d28a2143a750c4a1/rundmc/runcontainerd/nerd/nerd.go#L43
) for process isolation.

**Comment by MarcPaquette** [comment]
Hi @fisherxu 
Any further questions on this issue or is it safe to close out?

**Comment by fisherxu** [comment]
> 

Sorry for the delay, no questions now,  let's close the issue :)
