### ISSUE TITLE
gdn binary is gone in 1.20.9 release assets

### ISSUE THREAD

**Issue by xtremerui** [cloudfoundry/garden-runc-release#231]
## Description

In 1.20.9 github release assets the `gdn` binary is missing comparing to 1.20.8. Not sure if it is intentional or mistake. 

If it is expected, please add a release note and i would consider it a breaking change since it will break CI that depends on the binary. And I couldn't find a document about building the binary from the .tgz either please help.

Thank you!

**Comment by MarcPaquette** [comment]
Hi @xtremerui,

I'm looking into this issue for you. I believe there may be an underlying issue that is impacting this release.

Thanks,
Marc

**Comment by MarcPaquette** [comment]
Hi @xtremerui,

This was a change in our release pipelines that had an unintended side effect of removing the gdn binary. We're going to make sure that it is included for releases going forward.  1.20.9 should be a one-off exclusion.

Thanks for bringing this to our attention!

--Marc

**Comment by mariash** [comment]
@xtremerui we were able to attach gdn to release 1.20.9. Sorry for interruption.
