### ISSUE TITLE
Release gdn binary for ARM

### ISSUE THREAD

**Issue by xtremerui** [cloudfoundry/garden-runc-release#238]
## Description

Just wondering if its possible to release a `gdn` binary that built for ARM based OS. So as a downstream, when building a ARM based binary itself, Concourse could include this ARM based `gdn` binary directly instead of build it from scrath.

With the golang cross compile feature, it might be as easy as `GOARCH=arm64 GOOS=linux go build ...`

**Comment by winkingturtle-vmw** [comment]
@xtremerui We added an arm64 binary to 1.22.9 version of garden-runc-release. Let us know if that solves your problem and we can add that to the CI task.

**Comment by xtremerui** [comment]
@winkingturtle-vmw thx a lot!
