### ISSUE TITLE
release 1.22.9 doesn't include gdn binary

### ISSUE THREAD

**Issue by xtremerui** [cloudfoundry/garden-runc-release#242]
Is it intended or a mistake? Thank you!

**Comment by MarcPaquette** [comment]
Taking a look into this issue.  We're migrating CI's to a new instance. Let me see if something fell through the cracks.

**Comment by winkingturtle-vmw** [comment]
@xtremerui I updated the release to contain the same binary that would've been built with the CI. We will make sure it's added back to the pipeline for next time.
