### ISSUE TITLE
App Instance uses all tcp memory of the cell

### ISSUE THREAD

**Issue by ampersand8** [cloudfoundry/garden-runc-release#27]
In our CF deployment, we experienced a situation where one app instance was
able to slow down dramatically the network traffic in a diego cell.

During investigation, we observed that the app was using all the available tcp
memory on the cell.

In `/var/log/kern.log` there were errors “TCP: out of memory”.
We observed that the tcp window was small observed through tcpdump. New connections were possible to be created, but no traffic due to the TCP window.

When we stopped the app instance everything was back to normal.

TCP memory was monitored through the `/proc/net/sockstat` file.

Interestingly, due to not-well written app, we observed high TCP memory usage
without seeing large number of TCP connection.

We are mitigating currently the issue  by increasing the TCP memory and by restarting the cell (or the app)
`cat /proc/sys/net/ipv4/tcp_mem` is the actual hard-limit we have per cell which currently is 20% of the total memory.

It will be great to limit how much tcp memory a container can use, as well as to have some statistics per container.

**Comment by julz** [comment]
sorry for the delayed response updating this issue. This is done and available in https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.8.0!
