### ISSUE TITLE
Stop testing for containerd-for-processes in CI

### ISSUE THREAD

**Issue by winkingturtle-vmw** [cloudfoundry/garden-runc-release#317]
## Description
Currently this is an [experimental feature](https://github.com/cloudfoundry/garden-runc-release/blob/eb20e6b9a8c111ef1dadab3156834a91a2ead73f/jobs/garden/spec#L231-L233). We are currently running tests for this feature set, but not actively using it. There is an [experimental opsfile in cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/ee8a88634bb4f933afbe1e152434163cab3843e6/operations/experimental/enable-containerd-for-processes.yml) that will turn this on. It's unclear if anyone in the community uses this opsfile. If all production software currently use only containerd_mode only without containerd for processes, we should stop testing this in CI and focus on containerd_mode only.

This issue is meant to generate discussion whether this will cause an issue for the community or not. Please comment below with question and thoughts.

**Comment by MarcPaquette** [comment]
Hey @winkingturtle-vmw,
With the rewrite of the CI pipelines, has this issue been resolved?
Thanks!

**Comment by winkingturtle-vmw** [comment]
Not yet, we are still testing for this. We still need to remove that from our pipelines.

**Comment by MarcPaquette** [comment]
Starting a community dialogue here: https://cloudfoundry.slack.com/archives/C02FL4A2K/p1707837985169509

**Comment by MarcPaquette** [comment]
Hey @winkingturtle-vmw,
In order to remove this we just need to remove the sections listed below from `wg-app-platform-runtime-ci`, correct?
```
$ ag containerd-for-processes
garden-runc-release/pipelines/garden-runc-release.yml
18:  - run-gats-with-containerd-for-processes
1383:- name: run-gats-with-containerd-for-processes
1404:      DEPLOYMENT_NAME: gats-with-containerd-for-processes
1416:      DEPLOYMENT_NAME: gats-with-containerd-for-processes
1450:            - run-gats-with-containerd-for-processes
1467:            - run-gats-with-containerd-for-processes

cpu-entitlement-plugin/pipelines/cpu-entitlement-plugin.yml
244:        {input-01/operations/experimental/enable-containerd-for-processes.yml,combined-assets/}

cpu-entitlement-plugin/index.yml
6:- enable-containerd-for-processes.yml
```

**Comment by MarcPaquette** [comment]
> Starting a community dialogue here: https://cloudfoundry.slack.com/archives/C02FL4A2K/p1707837985169509

FWIW: No one really spoke up regarding it's usage.

**Comment by winkingturtle-vmw** [comment]
> Hey @winkingturtle-vmw, In order to remove this we just need to remove the sections listed below from `wg-app-platform-runtime-ci`, correct?
> 
> ```
> $ ag containerd-for-processes
> garden-runc-release/pipelines/garden-runc-release.yml
> 18:  - run-gats-with-containerd-for-processes
> 1383:- name: run-gats-with-containerd-for-processes
> 1404:      DEPLOYMENT_NAME: gats-with-containerd-for-processes
> 1416:      DEPLOYMENT_NAME: gats-with-containerd-for-processes
> 1450:            - run-gats-with-containerd-for-processes
> 1467:            - run-gats-with-containerd-for-processes
> 
> cpu-entitlement-plugin/pipelines/cpu-entitlement-plugin.yml
> 244:        {input-01/operations/experimental/enable-containerd-for-processes.yml,combined-assets/}
> 
> cpu-entitlement-plugin/index.yml
> 6:- enable-containerd-for-processes.yml
> ```

Yes. We also need to [stop running those test in guardian](https://github.com/cloudfoundry/guardian/blob/main/bin/test.bash#L23-L24)
