### ISSUE TITLE
Missing gdn binaries in release assets for 1.46

### ISSUE THREAD

**Issue by xtremerui** [cloudfoundry/garden-runc-release#329]
## Description
Hi, we noticed the latest release [v1.46](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.46.0) doesn't include ` gdn-*` and `gdn-arm64-*` binaries anymore. Not sure if it is a CI bug or intentional. Thank you!

**Comment by MarcPaquette** [comment]
@winkingturtle-vmw,
Did our Migration to the OSS CI Export introduce this issue?

**Comment by winkingturtle-vmw** [comment]
Yes indeed. I just published [1.47.0](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.47.0) with fixed tooling. Note that the blob name will now be different. e.g  `gdn-linux-amd64-1.47.0`  and  `gdn-linux-arm64-1.47.0`
