### ISSUE TITLE
Busybox blob is unversioned

### ISSUE THREAD

**Issue by ryanmattcollins** [cloudfoundry/garden-runc-release#34]
In `config/blobs.yml`, one of the blobs being used is `busybox/busybox.tar.gz`. Is there any chance   someone can add a version to that blob to match the rest of the blobs in the yml? We're unable to determine what version of busybox is being used.

**Comment by teddyking** [comment]
I'm not entirely sure we actually know the version of that blob ...
The [packaging](https://github.com/cloudfoundry/garden-runc-release/blob/f2f2f412fdfaf51521ee43410093267fcb03fffb/packages/busybox/packaging#L3-L12) for the blob suggests it was just generated at some point in the past.

We actually have a [chore](https://www.pivotaltracker.com/story/show/138808743) to get rid of that blob entirely as it's not used by prod deployments. Are you explicitly depending on it for any reason?

**Comment by ryanmattcollins** [comment]
Nope! We actually just needed the version for Licensing purposes. If it's scheduled to be removed, that's helpful for us. Any idea when that will happen? If it is being shipped with the garden runc release we have to disclose it (even if it's not actually being used).

**Comment by teddyking** [comment]
Hey @ryanmattcollins,

We decided to keep the busybox blob in the end. We've bumped it to v1.26.2 and named the blob so that it is easy to identify the version.

Thanks!
Ed
