### ISSUE TITLE
Ducati is not a thing

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/garden-runc-release#35]
The [diagram here](https://github.com/cloudfoundry/garden-runc-release/blob/develop/docs/components.png) refers to an imaginary component called "Ducati."

Ducati is in the attic.  We don't talk about Ducati anymore.

The new thing is [CF Networking Release](https://github.com/cloudfoundry-incubator/cf-networking-release) which has a [garden external networker](https://github.com/cloudfoundry-incubator/cf-networking-release/tree/develop/src/garden-external-networker) that allows any CNI plugin to be a garden networker.

Let's update the diagram!

**Comment by teddyking** [comment]
But Ducati has such a good name!

**Comment by teddyking** [comment]
Thanks! The diagram has been updated.
