### ISSUE TITLE
Should docker/docker be updated or vendored as a submodule?

### ISSUE THREAD

**Issue by kdykeman** [cloudfoundry/garden-runc-release#49]
## Description

I'm not sure if changes have made it upstream, but src/github.com/docker/docker is currently over five months behind. Should that be updated or submoduled in vs. copied?

**Comment by glestaris** [comment]
Hello @kdykeman, we are in the process of deprecating [Garden Shed](http://github.com/cloudfoundry/garden-shed) (the only component of Garden-runC that's consuming `docker/docker`) in favour of [GrootFS](http://github.com/cloudfoundry/grootfs-release). While not announced yet, we hope to do so by mid/late Nov. Hence, `docker/docker` will soon be removed from the Garden-runC BOSH release.

**Comment by glestaris** [comment]
Closing this.
