### ISSUE TITLE
Is there a way to deploy garden-runc locally without bosh-lite?

### ISSUE THREAD

**Issue by kreamyx** [cloudfoundry/garden-runc-release#50]
## Description

I am trying out garden-runc and I have been following the github README. I was wondering if there is an easy way to deploy garden-runc on a local machine without the need for virtual box and bosh-lite?

**Comment by evanfarrar** [comment]
It is possible to run garden-runc without virtualbox, directly on your desktop, if you run Linux on your desktop (at least for the linux variant of garden, but garden-runc for windows would require windows server 2016). You can boot the server and make API calls against it or use gaol to create containers.

garden-runc-release is a BOSH package, and you need to use either `bosh create-env` or a BOSH director to deploy it. Using bosh to deploy it will make it much simpler to find a compatible version of linux to run it on as the Linux API can change version to version, so if you are just getting started, it really is the easiest way to get started.

bosh-lite uses garden-runc, so if you want to learn about garden-runc, you can also just install that, on any IaaS you prefer (or virtualbox).

**Comment by kreamyx** [comment]
Alright thanks for helping out!

**Comment by rosenhouse** [comment]
@kreamyx In case you were looking for a link, the garden-runc binary being referenced is build from the [Guardian](https://github.com/cloudfoundry/guardian/) source repo.  I believe the `cmd/gdn` binary is the Garden API server.

**Comment by teddyking** [comment]
@kreamyx You may also find this [rootless doc](https://github.com/cloudfoundry/garden-runc-release/blob/develop/docs/rootless-containers.md) useful. It contains a step-by-step guide for running garden on a vanilla ubuntu server. The guide is targeted at setting up garden for rootless mode, but the steps are pretty much the same for just getting the server up and running

**Comment by kreamyx** [comment]
That's great! thanks a lot
