### ISSUE TITLE
Droplet with big symlink failed to deploy with grootfs: Cannot create symlink to: File name too long

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/garden-runc-release#63]
> Note: This issue comes from the discussion in slack in: https://cloudfoundry.slack.com/archives/C033RE5D6/p1521478035000065
>
> The problem has been identified and diagnosed and it is unlikely to happen again. Opening this ticket for documentation and reference as requested by @julz .

## Description

While upgrading our CF deployment, which included upgrade `garden-runc-release` from v1.9.6 to v1.11.1 and introduce `grootfs`, one application failed restarting after eviction, with the following error in the `cf events`:

`Copying into the container failed: stream-in: nstar: error streaming in: exit status 2. Output: tar: ./app/.cfignore: Cannot create symlink to '# Byte-compiled / ....' File name too long\ntar: Exiting with failure`

(see below for the full error).

This was caused by the bug described in https://github.com/cloudfoundry/cli/issues/1349. A spurious file was created in the droplet with a very very long file target (it was using the content of the target file, rather than the path).  

But it was working fine with garden  v1.9.6, started to fail with v1.11.1 after introducing `grootfs`.

Pushing the application again with a newer version of cf-cli would result in a valid symlink and would fix the problem.

## Logging and/or test output

The full error is:

```
            "metadata": {
               "instance": "55ee4080-fc4e-4f63-48e0-daeb",
               "index": 1,
               "reason": "CRASHED",
               "exit_description": "Copying into the container failed: stream-in: nstar: error streaming in: exit status 2. Output: tar: ./app/.cfignore: Cannot create symlink to '# Byte-compiled / optimized / DLL files\\n__pycache__/\\n*.py[cod]\\n*$py.class\\n\\n# C extensions\\n*.so\\n\\n# Distribution / packaging\\n.Python\\nenv/\\nbuild/\\ndevelop-eggs/\\ndist/\\ndownloads/\\neggs/\\n.eggs/\\nlib/\\nlib64/\\nparts/\\nsdist/\\nvar/\\nwheels/\\n*.egg-info/\\n.installed.cfg\\n*.egg\\n\\n# PyInstaller\\n#  Usually these files are written by a python script from a template\\n#  before PyInstaller builds the exe, so as to inject date/other infos into it.\\n*.manifest\\n*.spec\\n\\n# Installer logs\\npip-log.txt\\npip-delete-this-directory.txt\\n\\n# Unit test / coverage reports\\nhtmlcov/\\n.tox/\\n.coverage\\n.coverage.*\\n.cache\\nnosetests.xml\\ncoverage.xml\\n*.cover\\n.hypothesis/\\n\\n# Translations\\n*.mo\\n*.pot\\n\\n# Django stuff:\\n*.log\\nlocal_settings.py\\n\\n# Flask stuff:\\ninstance/\\n.webassets-cache\\n\\n# Scrapy stuff:\\n.scrapy\\n\\n# Sphinx documentation\\ndocs/_build/\\n\\n# PyBuilder\\ntarget/\\n\\n# Jupyter Notebook\\n.ipynb_checkpoints\\n\\n# pyenv\\n.python-version\\n\\n# celery beat schedule file\\ncelerybeat-schedule\\n\\n# SageMath parsed files\\n*.sage.py\\n\\n# dotenv\\n.env\\n\\n# virtualenv\\n.venv\\nvenv/\\nENV/\\n\\n# Spyder project settings\\n.spyderproject\\n.spyproject\\n\\n# Rope project settings\\n.ropeproject\\n\\n# mkdocs documentation\\n/site\\n\\n# mypy\\n.mypy_cache/\\n\\n.direnv\\n.envrc\\n': File name too long\ntar: Exiting with failure status due to previous errors\n",
               "crash_count": 1,
               "crash_timestamp": 1519298150947758085,
               "version": "1f6aa9e0-a404-41bb-b6ec-67620be0febd"
            },
```
## Steps to reproduce

 * Using garden-runc-release v1.9.6 
 * Push an app using `cf v3-push` with cf-cli v6.32.0, including with symbolic link to the absolute path of file > 1kb:

```
dd count=2 bs=1024 if=/dev/urandom of=- | base64 > foo
ln -s $(pwd)/foo bar
cf-6.32.0 v3-push -p . myapp
```
 
 * Upgrade to garden-runc-release v1.11.1. The application would fail restarting after eviction.

**Comment by keymon** [comment]
As @julz commented:

> I’d almost (almost) bet that’s what’s happening: some old version accidentally symlinked to an incredibly long filename, got uploaded, worked because on the remote server it doesnt really matter if cfignore was corrupt, now breaks on xfs because containers/droplets don’t isolate us from kernels and filesystems
> I’m kind of surprised xfs would have a particular limit that ext4 doesnt, but that almost has to be what’s going on

Regarding the xfs limit, I found https://stackoverflow.com/a/36759498 , and it seems that the max length in xfs is : https://github.com/torvalds/linux/blob/abc36be236358162202e86ad88616ff95a755101/fs/xfs/libxfs/xfs_format.h#L1219

For ext4 it seems to be the length of the maximum path, so 4096: https://github.com/torvalds/linux/blob/ead751507de86d90fa250431e9990a8b881f713c/include/uapi/linux/limits.h#L13

**Comment by julz** [comment]
Thanks @keymon, glad we got to the bottom of this one!
