### ISSUE TITLE
bosh fails to render ERB templates in recent garden-runc releases

### ISSUE THREAD

**Issue by spikymonkey** [cloudfoundry/garden-runc-release#67]
# Description

Trying to deploy garden-runc 1.12.1 today, we hit the following as bosh tried to render the ERB templates:

```
Task 2485 | 09:16:12 | Error: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'worker'. Errors are:
     - Unable to render templates for job 'garden'. Errors are:
       - Error filling in template '(unknown)' (line (unknown): garden/bin/garden_start.erb:4: syntax error, unexpected ';'
      -; _erbout.concat "\n#!/usr/bin...
        ^)
       - Error filling in template '(unknown)' (line (unknown): garden/config/config.ini.erb:31: syntax error, unexpected ';'
      -; _erbout.concat "\n[server]\n; apparmor\n"
        ^
      garden/config/config.ini.erb:34: syntax error, unexpected ';'
      ;  if apparmor_profile_provided -; _erbout.concat "\n  apparmor = "
                                        ^
      garden/config/config.ini.erb:36: syntax error, unexpected keyword_end, expecting end-of-input
      ;  end -; _erbout.concat "\n\n; bin...
            ^)
```

We're guessing that the templates have begun to use ERB syntax that is only supported by recent versions of bosh. We're on v257.3. We were previously able to deploy garden-runc 1.9.0 so the breaking change must been introduced somewhere between 1.9.0 and 1.12.1. 

# Environment

* garden-runc-release version: 1.12.1
* IaaS: vsphere
* Stemcell version: bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.17
* Kernel version: 4.4.0-109-generic

# Steps to reproduce

Attempt to deploy garden-runc 1.12.1 with bosh v257.3

# Resolution

We'll attempt to upgrade our bosh. But it'd be helpful if garden could publish a minimum version requirement, or maybe the ERB could be reworked to allow the garden-runc release to work on older boshes?

**Comment by teddyking** [comment]
I'm pretty sure (based on no evidence whatsoever) that it's probably the fact that we're using `-%>` to close erb tags in the [config.ini.erb](https://github.com/cloudfoundry/garden-runc-release/blob/v1.12.1/jobs/garden/templates/config/config.ini.erb#L31) template.

**Comment by spikymonkey** [comment]
Yep you have one in [garden-start.erb](https://github.com/cloudfoundry/garden-runc-release/blob/ed4b30d20632e3909e0e24f4e1b7cac80748d697/jobs/garden/templates/bin/garden_start.erb#L4) too - seems pretty likely.

**Comment by Callisto13** [comment]
@spikymonkey we have found that the erb trim feature was introduced in [BOSH v260](https://github.com/cloudfoundry/bosh/blob/v260/bosh-director-core/lib/bosh/director/core/templates/source_erb.rb#L11) following this [PR](https://github.com/cloudfoundry/bosh/pull/1482).
as it is quite old (oct 2016) we are still considering whether we should be supporting that far back, or if we should be clear about minimum bosh version.
we'll let you know soon :)

**Comment by spikymonkey** [comment]
Thanks @Callisto13. We should definitely upgrade our bosh too :)

**Comment by julz** [comment]
Hi @spikymonkey - since [the cf-deployment folk require at least Bosh v262](https://www.pivotaltracker.com/story/show/156567310/comments/188706960) I don't think we can justify work to support older versions than that in Garden. I'm going to close this issue, please do let us know if upgrading Bosh doesn't fix the problem!

**Comment by spikymonkey** [comment]
Hi @julz, makes complete sense. Cheers!
