### ISSUE TITLE
garden execution failed during fresh CF deployment: mount: Structure needs cleaning

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry/garden-runc-release#68]
# Description
I tried to deploy Cloud Foundry and failed during the creation of one cell instance. When i log into the failed cell and do a monit summary i get the following output:

`
Process 'consul_agent'              running
Process 'rep'                       running
Process 'garden'                    Execution failed
Process 'route_emitter'             running
Process 'metron_agent'              running
System 'system_localhost'           running
`

In the CF deployment are two other cell instances running. One of them seems to be empty as there is only `system_localhost` running but the other run works as expected. The desired amount of cells for the CF deployment is 3.

I couldn't find anything special under /var/vcap/sys/log/garden.
The logs under /var/vcap/sys/log/monit shows "exit status 32: mount: Structure needs cleaning".

I executed the analize script you provided me through slack (https://raw.githubusercontent.com/cloudfoundry/garden-runc-release/develop/scripts/ordnance-survey) and found out the file `/var/vcap/jobs/garden/config/config.ini` your script expects to find is not present on the instance.
(i commented the line with `/var/vcap/jobs/garden/config/config.ini ` out and downloaded the report, the .tgz is attached underneath).

# Environment

* garden-runc-release version: 1.11.1
* IaaS: vSphere
* Stemcell version: bosh-vsphere-esxi-ubuntu-trusty-go_agent 3541.9
* Kernel version: 4.4.0-116-generic

# Logs
logs from monit and garden https://gist.github.com/gdenn/764af3b8ce92fe063168413b45931833

best,
Dennis

**Comment by julz** [comment]
Sorry about this, looks like this issue got lost between the cracks in our issue tracker. Were you ever able to get to the bottom of this?

**Comment by gdenn** [comment]
I think we updated to the next version of either the stemcell or the garden-runc and the problem was gone. But i can't remember exactly, sry.

**Comment by julz** [comment]
Thanks @gdenn, glad to hear you're ok even if we're not sure how!
