### ISSUE TITLE
/some/path is not a mount point

### ISSUE THREAD

**Issue by teddyking** [cloudfoundry/garden-runc-release#71]
# Description

After upgrading to garden-runc-release v1.13.0 I'm seeing the following errors in my logs:

```
/var/vcap/data/baggageclaim/volumes/live/c6e9cb7f-1be9-4d78-48a6-b5903816a20b/volume is not a mount point
```

# Environment

* garden-runc-release version: 1.13.0
* IaaS: Not applicable / all
* Stemcell version: Not applicable / all
* Kernel version: Not applicable / all

# Steps to reproduce

TBC

# Logs

```
/var/vcap/data/baggageclaim/volumes/live/c6e9cb7f-1be9-4d78-48a6-b5903816a20b/volume is not a mount point
```

# Cause

There is a known regression related to garden's handling of bind mounts in v1.13.0.

# Resolution

Do not use v1.13.0, and instead bump directly to v1.13.1.

**Comment by BooleanCat** [comment]
@teddyking can we close this?
