### ISSUE TITLE
Error occurs while Installing Cloud Foundry, DIEGO on CentOs.

### ISSUE THREAD

**Issue by JY-Lee** [cloudfoundry/garden-runc-release#80]
Hi,

An error occured while installing Cloud Foundry, DIEGO on **CentOs**..

The versions i have used for Release and BOSH are listed below.
+++++++++++++++++++++++++++++++++++
BOSH-CLI v2

BOSH-RELEASE 264.7.0

CF-RELEASE 287

DIEGO-RELEASE 1.34.0

GARDEN-RUNC 1.11.0

CFLINUX-RELEASE 1.185.0
+++++++++++++++++++++++++++++++++++++
And I used Stemcell image v 3468.21 in **CentOs** environment.

This settings have worked on Ubuntu. Apparently not on **CentOs**.

When errors occur while installing Cloud Foundry, it was solved as i had access to logs and script files could be edited. 
However, i have no idea how to deal with DIEGO installation issues.

My major quetions are:

## 2. Is it able to use "apparmor-paser" while installing DIEGO Cell on **CentOs**? 

In case of normal installation, it throws an error saying "apparmor_parser: command not found" 

If i install package directly on DIEGO cell VM and execute : apparmor_parser -r "/var/vcap/jobs/garden/config/garden-default" >> it responds with "no cache value on read/write"

## 3. If i try to install without the "apparmor" section by annotating them out:

rep throws an error 
#######################
Failed: 'cell_z1/d30f7487-f7ea-42fa-b9a6-a6af4a9f6c6b (0)' is not running after update. Review logs for failed jobs: rep (00:04:21)

Error 400007: 'cell_z1/d30f7487-f7ea-42fa-b9a6-a6af4a9f6c6b (0)' is not running after update. Review logs for failed jobs: rep
#######################

Log as below is found at rep_ctl.log
#######################
Not setting /proc/sys/net/ipv4 parameters, since I'm running inside a linux container
#######################

Log as below is found at garden.stdout.log
#######################
Version:1.0 StartHTML:0000000105 EndHTML:0000028323 StartFragment:0000000433 EndFragment:0000028283
{"timestamp":"1528181050.931253672","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.start","log_level":0,"data":{"cause":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 40\\\"\"\n","handle":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","session":"476.4.2.1"}}
{"timestamp":"1528181050.945348501","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.starting","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 40\\\"\"\n","handle":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","imageID":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","original_timestamp":"2018-06-05T06:44:10.945072896Z","session":"476.4.2.1"}}
{"timestamp":"1528181050.945517778","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.deleting-image.starting","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 40\\\"\"\n","handle":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","id":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","imageID":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","original_timestamp":"2018-06-05T06:44:10.94520064Z","session":"476.4.2.1","storePath":"/var/vcap/data/grootfs/store/unprivileged"}}
{"timestamp":"1528181050.945569754","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.deleting-image.overlayxfs-destroying-image.starting","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 40\\\"\"\n","handle":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","id":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","imageID":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","imagePath":"/var/vcap/data/grootfs/store/unprivileged/images/executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","original_timestamp":"2018-06-05T06:44:10.945269248Z","session":"476.4.2.1","storePath":"/var/vcap/data/grootfs/store/unprivileged"}}
{"timestamp":"1528181050.953394413","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.deleting-image.overlayxfs-destroying-image.ending","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 40\\\"\"\n","handle":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","id":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","imageID":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","imagePath":"/var/vcap/data/grootfs/store/unprivileged/images/executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","original_timestamp":"2018-06-05T06:44:10.953026048Z","session":"476.4.2.1","storePath":"/var/vcap/data/grootfs/store/unprivileged"}}
{"timestamp":"1528181050.953512192","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.deleting-image.ending","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 40\\\"\"\n","handle":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","id":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","imageID":"executor-healthcheck-5be43913-6810-4018-59a3-8bf1af14555c","original_timestamp":"2018-06-05T06:44:10.953161728Z","session":"476.4.2.1","storePath":"/var/vcap/data/grootfs/store/unprivileged"}}
#######################

Anyone familer with this issue? **Thank you in advance**.

**Comment by julz** [comment]
Hi @JY-Lee - as of right now Garden does not support CentOS, because we require a kernel version of at least 3.19 (and because we have no CI for centOS, so wouldn't be confident that we wouldn't regress on any support we added). Is there a reason you particularly need CentOS? You may have a lot more success with Ubuntu or SUSE as these are what the major production users of Cloud Foundry use, and what most development teams test with.
