### ISSUE TITLE
vendor golang using bosh package

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/garden-runc-release#92]
Hey y'all

Not so much of an issue as a `nice to have` - would be great if you switched your current golang packages that you've written the packaging for over to the bosh vendor package version of golang-release.

if you switch to [this](https://github.com/bosh-packages/golang-release/tree/master/packages/golang-1-linux) it should make it WAY easier for you to bump golang versions in the future (could even be automatically done in ci as `bosh vendor package` is idempotent.

[directions on bosh vendor package](https://bosh.io/docs/package-vendoring/#vendor)

[routing release as an example of the switch](https://github.com/cloudfoundry/routing-release/blob/develop/packages/gorouter/packaging#L3)

**Comment by BooleanCat** [comment]
> if you switch to this it should make it WAY easier for you to bump golang versions in the future

In reality we bump golang so infrequently (at whatever cadence golang ship new versions) that there isn't really any pain associated with bumping to the latest golang. It takes us much longer to bump golang in our OTHER CI stuff (like docker images etc.). The bumping of the bosh package is fairly trivial.

Outside of this, I'd have a concern over not having direct control over bumping Go's vendored package to the latest version. In most cases Garden bumps Go within a few days of new versions shipping.

I would say this is my opinion and not necessarily the Garden team's opinion.

@Callisto13 @gcapizzi @danail-branekov @yulianedyalkova @georgethebeatle @ostenbom Thoughts?

**Comment by Callisto13** [comment]
I would echo @BooleanCat's concern about not having control over how quickly we bump, we like to get on it asap, but after a quick glance at the [golang-release](https://github.com/bosh-packages/golang-release) it doesn't look like they were too far behind 1.11's date. One thing I would like to see is finer grained version choice in the release: they only seem to package major.minor Go versions, but no patches. The patch bumps seem to be done by just bumping the minor package, which doesn't help with visibility or offer individual team control over rolling back to a previous patch if the new one manifests issues (which I recalled happened recently, 1.10.3 was it?).
I think we should have a team discussion over the merits next retro.
