### ISSUE TITLE
Disk quota concerns when moving from garden-shed to GrootFS

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/garden-runc-release#93]
# Description

I would like to understand how I can ensure apps have enough disk space when redeploying my CF deployment in order to migrate from garden-shed to GrootFS as I've heard there was a change in the way disk quota is calculated between garden-shed and GrootFS.

I see no mention of this explicitly in this document and believe it'd be a good place for it to live: https://github.com/cloudfoundry/garden-runc-release/blob/develop/docs/understanding_grootfs_store_disk_usage.md

# Environment

* garden-runc-release version: any where enabling the GrootFS image plugin is an option
* IaaS: *
* Stemcell version: *
* Kernel version: *

**Comment by Callisto13** [comment]
New documentation to address this gap can be found [here](https://github.com/cloudfoundry/garden-runc-release/blob/develop/docs/migrating-from-garden-shed-to-grootfs.md)
