### ISSUE TITLE
Cannot destroy a container with a `init still running error`

### ISSUE THREAD

**Issue by xtreme-bozhidar-lenchov** [cloudfoundry/garden-runc-release#95]
# Description

High load was observed on a diego cell in PWS. Diego and Garden teams investigated the noticed:

```
"guardian.api.garden-server.destroy.failed","data":{"error":"runc: exit status 1: container init still running\n","handle":"313deeee-dee5-4bee-4dd2-51e6","session":"1.1.73312"}}
```

Defunct envoy processes (again):
```
4294967+ 2196130       1  0 12:53 ?        00:00:00 [garden-init]
4294967+ 2196672 2196130  0 12:53 ?        00:00:00  \_ [envoy] <defunct>
4294967+ 2198005       1  0 12:53 ?        00:00:00 [garden-init]
4294967+ 2198316 2198005  0 12:53 ?        00:00:00  \_ [envoy] <defunct>
4294967+ 2229631       1  0 12:58 ?        00:00:00 [garden-init]
4294967+ 2231245 2229631  0 12:58 ?        00:00:00  \_ [envoy] <defunct>
```

# Environment

* garden-runc-release version: 1.16.3
* IaaS: AWS
* Stemcell version: Xenial 97.15
* Kernel version: 4.15.0-33-generic

# Steps to reproduce

Max containers reached message observed in CI jobs when apps fell onto problematic cell. Diego and Garden pointed to [existing story](https://www.pivotaltracker.com/n/projects/1158420/stories/154177609).

# Logs

Bosh logs and ordnance survey tarball were collected by CloudOps and are available for private sharing upon request.

# Cause

@jvshahid hypothesized about the cause in [story comment here](https://www.pivotaltracker.com/story/show/154177609/comments/194213541).

**Comment by julz** [comment]
Hi @xtreme-bozhidar-lenchov - thanks for reporting! We think this should be fixed in [GRR v1.16.4](
https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.16.4).
