### ISSUE TITLE
runc run: exit status 1: write /run/runc/<uid>/state.json: no space left on device

### ISSUE THREAD

**Issue by Callisto13** [cloudfoundry/garden-runc-release#97]
# Environment

* garden-runc-release version: any
* Stemcell: Xenial
* Kernel version: 4.10...4.15

# Issue encountered when...
Creating and deleting a lot of containers.

# Logs and symptoms
`runc run: exit status 1: write /run/runc/<uid>/state.json: no space left on device`

```sh
df -h | grep run
tmpfs           300M  300M     0 100% /run

du -h /run
270M    /run/udev/data

ls /run/udev/data | grep "cgroup:xfs_inode" | wc -l
693030 # or some large number

# or on Concourse workers
ls /run/udev/data | grep "cgroup:btrfs_inode" | wc -l
134307 # or some large number

# the above '_inode' entries will not be the only ones present, but they will constitute
# a big chunk of the usage. btrfs and xfs entries stand out in the context of garden
# created containers.
```

# Cause

[Slab](http://www.secretmango.com/jimb/Whitepapers/slabs/slab.html) resources are allocated for every container creation, but are not removed when containers are deleted because of a lack of "memory pressure" (on kernel 4.10*).

Representations of these allocations can be seen under `/sys/kernel/slab/*/cgroup`.
`udev` records information about slabs in its database therefore the absence of removals was filling the `/run` tmpfs.

_* we have not yet narrowed down which kernel commits introduced the change which allocates slab resources for kernel objects created for a container, but are sure of in a range a range between 4.4...4.10_

# Resolution
This is not a problem caused by Garden, but by the kernel and our investigation is **ongoing**. There is **no solid resolution yet**, but a work-around solution is detailed below.

It is partially resolved by kernel 4.11+, see [patch](https://github.com/torvalds/linux/commit/290b6a58b78be709e734d7fbeb1aa0416d9d41bc) and [investigation](https://www.pivotaltracker.com/n/projects/1158420/stories/155323866), but incidents have been reported on 4.15 (in Xenial stemcells) almost exclusively on **Concourse workers**. We are [working with Canonical](https://www.pivotaltracker.com/n/projects/1158420/stories/162980925) to try and pinpoint the issue.

To clear the slabs and free space in `/run`, run `udevadm info --cleanup-db`. **Note: Use with caution**. This will only clear the DB and may mask an actual underlying leak.

Another solution for issues seen on 4.15, is to ensure that VMs are deployed with a larger `/run` tmpfs (>=2GB). Anecdotal evidence suggests that 4GB is a good choice; those who have bump to 4GB have not seen a reoccurrence since.

# Action

**Please let us know on this thread if you encounter this issue**

To debug and confirm that this is your  issue, inspect `/run/udev/data` and `/sys/kernel/slab` and run `udevadm monitor` to watch for allocation events over multiple container creations and deletions.
Please do not paste vast amounts of output, but explain concisely what you have seen along with the following details:
- Garden-Runc version
- Environment (Concourse/Cloud Foundry)
- Stemcell version
- IAAS
- Size of `/run` tmpfs (`df -h | grep run`)

If possible, please also run `curl bit.ly/garden-ordnance-survey -sSfL | bash` and attach the resulting tar to your comment, or find a way to send it to us if you cannot attach. (If you are running GRR 1.17.2 or later, this program can be found on your vm at `/var/vcap/packages/dontpanic/bin/dontpanic`.) This is proving very hard to reproduce, so if you are able to, please keep your environment around for us to investigate.

The Garden team can also be found on the open source CloudFoundry slack in #garden, 0900-1800GMT.

If you have seen the error `write /run/runc/<uid>/state.json: no space left on device` and have found no evidence of either udev or slab problems, please search for or open a different issue.

**Comment by cirocosta** [comment]
Hi @Callisto13 , thanks so much for taking the time from the team to do the necessary exploration!

I see that the story was marked as accepted, but I can't see a clear resolution 🤔

Does that mean that we should keep track of the activity in the Pivotal Tracker story instead?

Thank you!

**Comment by Callisto13** [comment]
Hey @cirocosta the story was marked "accepted" by mistake I think.
There is no resolution yet.
Are you experiencing this problem now?

**Comment by cirocosta** [comment]
Hi @Callisto13 , thanks for the quick reply!

It never happened to our team's installations, but we've heard from customers getting to the same state as described in the issue.

Thanks!

**Comment by Callisto13** [comment]
Okay I see. Per the instructions above, could you get the following information from each incidence you have encountered:

- Garden-Runc version
- Environment (Concourse/Cloud Foundry)
- Stemcell
- IAAS
- Size of `/run` tmpfs (`df -h | grep run`)

Thanks

**Comment by Callisto13** [comment]
Due to lack of conclusive data and difficulty in reliable reproduction, it is very likely that we are going to close our ticket with [Canonical](https://www.pivotaltracker.com/story/show/162980925). This bug will stay open as it is not solved; resolutions (of a sort) are detailed above in the opening comment.

Investigations will open again if we receive one of the following:
- A bullet-proof reproduction template
- Instances of this occurring regularly and disruptively in production environments, with the workaround resolutions offering no improvement

If anyone sees this regularly in a **dev** environment, let me know: I have a test kernel with your name on it ;)
